v0/pipeline.json
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/template.json

Serverless 2.0 all steps included in schema
This PR includes changes for following steps-
- Serverless Prepare Rollback
- Serverless Deploy
- Serverless Package
- Serverless Rollback

feat:[CDS-73551]: Serverless 2.0 all steps Static Schema Changes

---

v0/pipeline/steps/cd/serverless-aws-lambda-deploy-v2-step-info.yaml
v0/pipeline/steps/cd/serverless-aws-lambda-deploy-v2-step-node.yaml
v0/pipeline/steps/cd/serverless-aws-lambda-package-v2-step-info.yaml
v0/pipeline/steps/cd/serverless-aws-lambda-package-v2-step-node.yaml
v0/pipeline/steps/cd/serverless-aws-lambda-prepare-rollback-v2-step-info.yaml
v0/pipeline/steps/cd/serverless-aws-lambda-prepare-rollback-v2-step-node.yaml
v0/pipeline/steps/cd/serverless-aws-lambda-rollback-v2-step-info.yaml
v0/pipeline/steps/cd/serverless-aws-lambda-rollback-v2-step-node.yaml
v0/template.json
v0/template/template_config.yaml

Serverless 2.0 all steps included in schema
This PR includes changes for following steps-
Serverless Prepare Rollback
Serverless Deploy
Serverless Package
Serverless Rollback

feat:[CDS-73551]: Serverless 2.0 all steps Static Schema Changes in Template Config File

---

v0/pipeline.json
v0/pipeline/stages/cd/services-yaml.yaml
v0/template.json

changed YamlSchemaType to only allow runtime inputs in ServicesYaml value field

feat:[CDS-71590]: changed YamlSchemaType to only allow runtime inputs in ServicesYaml value field

---

v0/pipeline.json
v0/pipeline/stages/cf/execution-wrapper-config.yaml
v0/pipeline/stages/custom/execution-wrapper-config.yaml
v0/template.json

Adding serverless 2.0 steps in cf and custom stages
This PR includes changes for following steps-
Serverless Prepare Rollback
Serverless Deploy
Serverless Package
Serverless Rollback

feat: [CDS-74092]: Adding serverless 2.0 steps in cf and custom stages

---

v0/pipeline.json
v0/pipeline/stages/cf/execution-wrapper-config.yaml
v0/pipeline/stages/custom/execution-wrapper-config.yaml
v0/template.json

Adding serverless 2.0 steps in cf and custom stages
This PR includes changes for following steps-
Serverless Prepare Rollback
Serverless Deploy
Serverless Package
Serverless Rollback

feat:[CDS-74092]: Adding serverless 2.0 steps in cf and custom stages

---

v0/pipeline.json
v0/pipeline/stages/cf/execution-wrapper-config.yaml
v0/pipeline/stages/custom/execution-wrapper-config.yaml
v0/pipeline/steps/cd/aws-cdk-bootstrap-step-info.yaml
v0/pipeline/steps/cd/aws-cdk-bootstrap-step-node.yaml
v0/template.json

feat: [CDS-73709]: update static schema
[CDS-73709]: https://harness.atlassian.net/browse/CDS-73709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [CDS-73709]: update static schema

---

v0/pipeline.json
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/pipeline/stages/cf/execution-wrapper-config.yaml
v0/pipeline/stages/custom/execution-wrapper-config.yaml
v0/pipeline/steps/cd/aws-cdk-synth-step-info.yaml
v0/pipeline/steps/cd/aws-cdk-synth-step-node.yaml
v0/template.json

[CDS-73713]: add static schema for AwsCdkSynth step
[CDS-73713]: https://harness.atlassian.net/browse/CDS-73713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CDS-73713]: add static schema for AwsCdkSynth step

---

v0/pipeline.json
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/pipeline/stages/custom/execution-wrapper-config.yaml
v0/pipeline/steps/cd/aws-cdk-diff-step-info.yaml
v0/pipeline/steps/cd/aws-cdk-diff-step-node.yaml
v0/template.json

feat: [CDS-73711]: add static schema for cdk diff step
[CDS-73711]: https://harness.atlassian.net/browse/CDS-73711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [CDS-73711]: add static schema for cdk diff step

---

v0/template.json
v0/template/template_config.yaml

add cdk steps

---

v0/pipeline.json
v0/pipeline/stages/cd/asg-deployment-meta-data.yaml
v0/pipeline/stages/cd/aws-lambda-deployment-meta-data.yaml
v0/pipeline/stages/cd/aws-sam-deployment-meta-data.yaml
v0/pipeline/stages/cd/azure-web-app-deployment-meta-data.yaml
v0/pipeline/stages/cd/custom-deployment-meta-data.yaml
v0/pipeline/stages/cd/deployment-stage-config.yaml
v0/pipeline/stages/cd/ecs-deployment-meta-data.yaml
v0/pipeline/stages/cd/elasti-group-deployment-meta-data.yaml
v0/pipeline/stages/cd/github-packages-artifact-config.yaml
v0/pipeline/stages/cd/kubernetes-deployment-meta-data.yaml
v0/pipeline/stages/cd/kubernetes-service-spec.yaml
v0/pipeline/stages/cd/manifest-configurations.yaml
v0/pipeline/stages/cd/native-helm-deployment-meta-data.yaml
v0/pipeline/stages/cd/native-helm-service-spec.yaml
v0/pipeline/stages/cd/serverless-aws-lambda-deployment-meta-data.yaml
v0/pipeline/stages/cd/ssh-deployment-meta-data.yaml
v0/pipeline/stages/cd/tas-deployment-meta-data.yaml
v0/pipeline/stages/cd/winrm-deployment-meta-data.yaml
v0/template.json

CD Static Schema Changes done
Error Message:
Pipeline schema validation Error : 'properties': {'deploymentType': {'const': 'GoogleCloudFunctions'}}}, 'then': {'properties': {'deploymentMetadata': {'': '#/definitions/pipeline/stages/cd/GoogleCloudFunctionDeploymentMetaData'}}}}, {'oneOf': [{'required': ['serviceConfig']}, {'required': ['service']}, {'required
link : https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/home/orgs/QE_Team/projects/Quality_Assurence/pipelines/pipelineschemavalidator/executions/ERKO6uIyQP6e4Csc6LjdQA/pipeline?storeType=INLINE

feat:[CDS-75858]: CD Static Schema Changes

---

v0/pipeline.json
v0/pipeline/steps/cd/serverless-aws-lambda-prepare-rollback-v2-step-info.yaml
v0/pipeline/steps/cd/serverless-aws-lambda-rollback-v2-step-info.yaml
v0/template.json

We had used wrong jsonignore in our step info , due to which it was appearing in our schema. We have used the correct jsonignore now

feat:[CDS-76094]: Removing DownloadManifestsFqn from schema

---

v0/pipeline.json
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/pipeline/stages/cf/execution-wrapper-config.yaml
v0/pipeline/stages/custom/execution-wrapper-config.yaml
v0/pipeline/steps/common/aws-cdk-bootstrap-step-info.yaml
v0/pipeline/steps/common/aws-cdk-deploy-step-info.yaml
v0/pipeline/steps/common/aws-cdk-destroy-step-info.yaml
v0/pipeline/steps/common/aws-cdk-diff-step-info.yaml
v0/pipeline/steps/common/aws-cdk-rollback-step-info.yaml
v0/pipeline/steps/common/aws-cdk-rollback-step-node.yaml
v0/pipeline/steps/common/aws-cdk-synth-step-info.yaml
v0/template.json
v0/template/template_config.yaml

[CDS-73718]: AWS CDK rollback schema, CDK steps schema update
[CDS-73718]: https://harness.atlassian.net/browse/CDS-73718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CDS-73718]: AWS CDK rollback schema, CDK steps schema update

---

v0/pipeline.json
v0/pipeline/stages/cd/services-yaml.yaml
v0/template.json

This is to support "useFromStage" in multi service setup

[feat]: [CDS-73601] : updating static schema for multi services propagation

---

v0/pipeline.json
v0/pipeline/stages/cd/artifactory-registry-artifact-config.yaml
v0/template.json
v0/trigger.json
v0/trigger/artifact_trigger/artifactory_registry.yaml

Adding a new field 'artifactFilter' for Artifactory artifact

[feat]: [CDS-78325]: Update schema, Add 'artifactFilter' Artifactory 

---

v0/pipeline.json
v0/pipeline/steps/cd/jenkins-build-step-info.yaml
v0/template.json

Adding not required field 'consoleLogPollFrequency' to JenkinsBuild step

[feat]: [CDS-78301]: Update schema add consoleLogPollFrequency Jenkins Build

---

v0/trigger.json
v0/trigger/trigger.yaml

Fix Triggers static schema for Org and Project Const

feat: [CDS-78816]: Fix Triggers static schema for Org and Project Const

---

v0/pipeline.json
v0/pipeline/steps/ci/build.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/ci/build.yaml
v1/template.json

[CDS-76887]: change type
[CDS-76887]: https://harness.atlassian.net/browse/CDS-76887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CDS-76887]: change type

---

v0/pipeline.json
v0/pipeline/steps/custom/harness-store.yaml
v0/template.json

Removing the required field file from harness store, which is breaking the save for CD steps in pipeline(Tanzu Command/ECS Run Task)

fix: [CDS-79231]: fix schema for harness store

---

v0/pipeline.json
v0/pipeline/steps/custom/output-alias.yaml
v0/pipeline/steps/custom/shell-script-step-info.yaml
v0/template.json

- [BE PR](https://github.com/harness/harness-core/pull/53086)
- tested the changes locally

feat:[CDS-79195]: shell script variables export

---

v0/pipeline.json
v0/pipeline/steps/cd/ecs-blue-green-create-service-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/ecs-blue-green-create-service-step-info.yaml
v1/template.json

Adding schema changes as I have two new fields to an existing step of type ECSBlueGreenCreateServiceStep in ECS swimlane.

[feat]: [CDS-79414]: added schema change for new fields to ecs blue green create service step

---

v0/pipeline.json
v0/pipeline/stages/approval/approval-stage-node.yaml
v0/pipeline/stages/cd/deployment-stage-node.yaml
v0/pipeline/stages/cf/feature-flag-stage-node.yaml
v0/pipeline/stages/ci/integration-stage-node.yaml
v0/pipeline/stages/custom/custom-stage-node.yaml
v0/pipeline/stages/custom/pipeline-stage-node.yaml
v0/pipeline/stages/iacm/iacmstage-node.yaml
v0/pipeline/stages/security/security-stage-node.yaml
v0/template.json

We have introduce the timeout config for Stages, Added the schema for timeout.

feat: [CDS-79932]: Added schema for timeout config for stage

---

v1/pipeline.json
v1/pipeline/common/policy-config.yaml
v1/pipeline/stages/custom/custom-stage-node.yaml
v1/pipeline/stages/custom/custom-stage-spec-element-wrapper-config.yaml
v1/pipeline/steps/custom/http-step-info.yaml
v1/pipeline/steps/custom/http-step-node.yaml
v1/pipeline/steps/custom/parallel-node.yaml
v1/pipeline/steps/custom/shell-script-step-info.yaml
v1/pipeline/steps/custom/shell-script-step-node.yaml
v1/pipeline/steps/custom/step-group-node.yaml
v1/template.json

Added yamls for parallel and group type for steps and fixed schema for http and shell script steps as per the RFC

feat: [CDS-80416]: fix static schema for steps in custom stage

---

v0/pipeline.json
v0/pipeline/steps/custom/autoApprovalParams.yaml
v0/pipeline/steps/custom/harness-approval-step-info.yaml
v0/pipeline/steps/custom/scheduledDeadline.yaml
v0/template.json
v0/trigger.json

Dev-tested the schema changes locally

feat:[CDS-81279]: autoApproval schema in harness approval

---

v0/pipeline.json
v0/pipeline/steps/cd/aws-sam-directory-manifest.yaml
v0/template.json
v1/examples/inputs/sample-pipeline-schema.json
v1/pipeline.json
v1/pipeline/steps/cd/aws-sam-directory-manifest.yaml
v1/template.json

Schema changes for adding samTemplateFile in SAM Manifest

feat:[CDS-80624]: Schema changes for adding samTemplateFile in SAM Manifest

---

v0/pipeline.json
v0/pipeline/stages/cd/amazon-s3-artifact-config.yaml
v0/template.json

Added fileFilter field for the S3 Artifact Source

[feat]:[CDS-81219]:Udated Schema Added fileFilter for S3

---

v0/pipeline.json
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/pipeline/steps/cd/asg-shift-traffic-step-info.yaml
v0/pipeline/steps/cd/asg-shift-traffic-step-node.yaml
v0/template.json
v0/template/template_config.yaml
v1/pipeline.json
v1/pipeline/stages/cd/execution-wrapper-config.yaml
v1/pipeline/steps/cd/asg-shift-traffic-step-info.yaml
v1/pipeline/steps/cd/asg-shift-traffic-step-node.yaml
v1/template.json
v1/template/template_config.yaml

feat: [CDS-82989]: added AsgShiftTraffic step

---

v0/pipeline.json
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/pipeline/stages/custom/execution-wrapper-config.yaml
v0/template.json

This is the source PR where we added support for GitHub actions for the CD and Custom stages. 
https://github.com/harness/harness-schema/pull/33/files

[CDS-82175]: Removed GitHub Action step from static schema for containerized CD Step Group

---

v1/pipeline.json
v1/pipeline/common/delegate.yaml
v1/template.json

updating stage delegate selector spec to be 
example:
```
delegate:
- selector1
- selector2
- selector3
```

[fix]: [CDS-81940]: updating stages common delegate selector field spec

---

v0/pipeline.json
v0/pipeline/stages/idp/execution-wrapper-config.yaml
v0/pipeline/steps/idp/idpcookiecutter-info.yaml
v0/pipeline/steps/idp/idpcookiecutter-node.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/stages/idp/execution-wrapper-config.yaml
v1/pipeline/steps/idp/idpcookiecutter-info.yaml
v1/pipeline/steps/idp/idpcookiecutter-node.yaml
v1/template.json

-> This is for adding the schema changes for idp cookicutter step in idp-stage.
-> Change is tested in local and is working as excpectd.

feat: [IDP-1437]: IDP Cookiecutter step schema changes

---

v0/pipeline.json
v0/pipeline/stages/idp/execution-wrapper-config.yaml
v0/pipeline/steps/idp/idpcreaterepo-info.yaml
v0/pipeline/steps/idp/idpcreaterepo-node.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/stages/idp/execution-wrapper-config.yaml
v1/pipeline/steps/idp/idpcreaterepo-info.yaml
v1/pipeline/steps/idp/idpcreaterepo-node.yaml
v1/template.json

-> This is the schema change for idpCreateRepo step which we are adding in IDP Stage.
-> Change is tested locally and working as expected.

feat: [IDP-1436]: Scheam changes for idp Create repo step

---

v0/pipeline.json
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/pipeline/stages/cf/execution-wrapper-config.yaml
v0/pipeline/stages/custom/execution-wrapper-config.yaml
v0/pipeline/steps/cd/download-aws-s3-step-info.yaml
v0/pipeline/steps/cd/download-aws-s3-step-node.yaml
v0/template.json
v0/template/template_config.yaml
v1/pipeline.json
v1/pipeline/stages/cd/deployment-stage-spec-element-wrapper-config.yaml
v1/pipeline/stages/cd/execution-wrapper-config.yaml
v1/pipeline/stages/cf/execution-wrapper-config.yaml
v1/pipeline/stages/custom/custom-stage-spec-element-wrapper-config.yaml
v1/pipeline/steps/cd/download-aws-s3-step-info.yaml
v1/pipeline/steps/cd/download-aws-s3-step-node.yaml
v1/template.json
v1/template/template_config.yaml

This is a generic s3 download step which will be used to download s3 buckets or folders or even a single file inside a container step group. For more details , please refer this doc
https://harness.atlassian.net/wiki/spaces/DEV/pages/21550334096/Download+S3+Store+Support+for+CD+Container+Based+Step+Group

feat:[CDS-84538]: Schema Changes for Generic Download Aws S3 Step for Container Step Group

---

v1/pipeline.json
v1/pipeline/stages/cd/environment-yaml-v2.yaml
v1/pipeline/stages/cd/infra-structure-definition-yaml.yaml
v1/pipeline/stages/cd/service-yaml-v2.yaml
v1/template.json

Changes
Changing title of svc + env + infra
deleting infraDefintion (without 's' from env schema)
changing name field to ref in svc + env
changing identifier to id in infra

[feat]: [CDS-85932] : update Service/Env/Infra static v1 yaml schema

---

v0/pipeline.json
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/pipeline/stages/cf/execution-wrapper-config.yaml
v0/pipeline/stages/custom/execution-wrapper-config.yaml
v0/pipeline/steps/cd/download-harness-store-step-info.yaml
v0/pipeline/steps/cd/download-harness-store-step-node.yaml
v0/template.json
v0/template/template_config.yaml
v1/pipeline.json
v1/pipeline/stages/cd/deployment-stage-spec-element-wrapper-config.yaml
v1/pipeline/stages/cd/execution-wrapper-config.yaml
v1/pipeline/stages/cf/execution-wrapper-config.yaml
v1/pipeline/stages/custom/custom-stage-spec-element-wrapper-config.yaml
v1/pipeline/steps/cd/download-harness-store-step-info.yaml
v1/pipeline/steps/cd/download-harness-store-step-node.yaml
v1/template.json
v1/template/template_config.yaml

Schema changes for Download Harness Store Step
For more details , please refer this doc
https://harness.atlassian.net/wiki/spaces/DEV/pages/21551744043/Download+Manifest+From+Harness+Store+in+CD+Container+Step+Group

feat:[CDS-84539]: Schema changes for Download Harness Store Step

---

v0/pipeline.json
v0/pipeline/steps/common/ssca-orchestration-step-info.yaml
v0/pipeline/steps/custom/sbom-drift.yaml
v0/template.json

Updated schema for sscaOrchestrationStepInfo for the required change of SbomDrift.

[SSCA-991] Update schema for sbomDrift in SscaOrchestrationStep

---

v1/examples/open_apis/execute_pipeline.txt
v1/examples/open_apis/execute_pipeline_stages_execution.txt
v1/examples/open_apis/rerun_pipeline_execution.txt
v1/examples/open_apis/rerun_pipeline_stages_execution.txt
v1/examples/open_apis/retry_pipeline_execution.txt

update examples in schema repo for execution api to accept json and yaml in inputs

feat: [CDS-88046]: update examples in schema repo for execution api to accept json and yaml in inputs

---

v1/pipeline.json
v1/pipeline/common/inputs.yaml
v1/pipeline/stages/cd/cd-inputs.yaml
v1/pipeline/stages/cd/deployment-stage-config.yaml
v1/pipeline/stages/cd/inherit-service.yaml
v1/pipeline/stages/cd/service-yaml.yaml
v1/pipeline/stages/cd/services-yaml.yaml
v1/template.json

pseudo structure
```
DeploymentStageConfig
services:
values:
- ServiceYaml or runtimeInput
inherit:  (in place of values)
```
```
ServiceYaml
ref: (required)
inputs: json or input node
```

[feat]: [CDS-87899] : services v1 yaml schema

---

v0/pipeline.json
v0/pipeline/steps/cd/download-aws-s3-step-info.yaml
v0/pipeline/steps/cd/download-harness-store-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/download-aws-s3-step-info.yaml
v1/pipeline/steps/cd/download-harness-store-step-info.yaml
v1/template.json

Schema changes for adding priviledged fields in Dowload Harness Store and Download Aws S3 step

Schema changes for adding priviledged fields in Dowload Harness Store and Download Aws S3 step

---

v0/pipeline.json
v0/pipeline/steps/cd/k8s-traffic-routing-provider-base-spec.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/k8s-traffic-routing-provider-base-spec.yaml
v1/template.json

Adding that name field for k8s traffic routing is mandatory and regenerating template and pipeline json files

[feat]: [CDS-88257]: updates to k8s traffic routing 

---

v0/pipeline.json
v0/pipeline/stages/cd/environment-group-metadata.yaml
v0/pipeline/stages/cd/environments-metadata.yaml
v0/template.json
v1/pipeline/stages/cd/environments-metadata.yaml

Update boolean field to accept both runtime as well as boolean value

feat:[CDS-86627]: update schema for env and env grp metatdata class

---

v1/pipeline.json
v1/pipeline/notification-channel-wrapper.yaml
v1/pipeline/notification_rules.yaml
v1/pipeline/pipeline_spec.yaml
v1/pipeline/pms-email-channel.yaml
v1/pipeline/pms-msteam-channel.yaml
v1/pipeline/pms-notification-channel.yaml
v1/pipeline/pms-pager-duty-channel.yaml
v1/pipeline/pms-slack-channel.yaml
v1/pipeline/pms-webhook-channel.yaml
v1/pipeline/stage_event.yaml

Adding notification rules schema for v1
**Testing:** Tested the generated schema locally against a v1 pipeline with notification rules.

feat: [CDS-88743]: notification rules schema

---

v0/pipeline.json
v0/pipeline/steps/cd/k8s-istio-provider-spec.yaml
v0/pipeline/steps/cd/k8s-route-spec.yaml
v0/pipeline/steps/cd/k8s-traffic-routing-destination.yaml
v0/pipeline/steps/cd/k8s-traffic-routing-destinations.yaml
v0/pipeline/steps/cd/k8s-traffic-routing-provider-base-spec.yaml
v0/pipeline/steps/cd/k8s-traffic-routing-rule.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/k8s-istio-provider-spec.yaml
v1/pipeline/steps/cd/k8s-route-spec.yaml
v1/pipeline/steps/cd/k8s-traffic-routing-destination.yaml
v1/pipeline/steps/cd/k8s-traffic-routing-destinations.yaml
v1/pipeline/steps/cd/k8s-traffic-routing-provider-base-spec.yaml
v1/pipeline/steps/cd/k8s-traffic-routing-rule.yaml
v1/template.json

[fix]: [CDS-88988]: updating traffic routing schema with support for runtime input for several fields

---

bundler/schema_store/src/main/java/io/harness/YamlEntityType.java
bundler/schema_store/src/main/java/io/harness/bundler/SchemaBundlerRegistrar.java
v1/service.json
v1/serviceEntity/artifact-source.yaml
v1/serviceEntity/artifact-wrapper.yaml
v1/serviceEntity/basic-artifact-config.yaml
v1/serviceEntity/basic-manifest-config.yaml
v1/serviceEntity/basic-service-spec.yaml
v1/serviceEntity/config-file.yaml
v1/serviceEntity/k8s-manifest.yaml
v1/serviceEntity/kubernetes-service-spec.yaml
v1/serviceEntity/manifest-config.yaml
v1/serviceEntity/manifest-wrapper.yaml
v1/serviceEntity/service-entity.yaml
v1/serviceEntity/service-spec.yaml
v1/serviceEntity/stores/basic-artifact-store-config.yaml
v1/serviceEntity/stores/basic-config-file-store-config.yaml
v1/serviceEntity/stores/basic-manifest-store-config.yaml
v1/serviceEntity/stores/docker-hub-artifact-config.yaml
v1/serviceEntity/stores/github-store-config.yaml
v1/serviceEntity/stores/harness-store.yaml
v1/serviceEntity/values-manifest.yaml

Derived from
https://harness.atlassian.net/wiki/spaces/~5ce42d90c9167e0d6ea29342/pages/21583530813/Service+Environment+Yaml+Simplification#Final-Service-Yaml
service type supported: kubernetes
manifest supported: k8s, values
manifest store supported : github
artifact supported: docker
config-file store - harness

[feat]: [CDS-87897] : new schema v1 for service entity crud

---

v0/pipeline.json
v0/pipeline/steps/cvng/verification-job-spec.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cvng/verification-job-spec.yaml
v1/template.json

Make deployment tag as opttional field in verify step

[fix]: [CDS-88580]: remove deployment tag as required field

---

v0/pipeline.json
v0/pipeline/common/harness-file-store-source.yaml
v0/pipeline/common/shell-script-inline-source.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/common/harness-file-store-source.yaml
v1/pipeline/common/shell-script-inline-source.yaml
v1/template.json

fix: [CDS-91468]: added yaml validation for omitted required fields

---

v0/pipeline.json
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/pipeline/steps/cd/asg-phased-deploy-step-info.yaml
v0/pipeline/steps/cd/asg-phased-deploy-step-node.yaml
v0/pipeline/steps/cd/asg-rollback-step-info.yaml
v0/pipeline/steps/cd/asg-rollback-step-node.yaml
v0/pipeline/steps/cd/asg-setup-step-info.yaml
v0/pipeline/steps/cd/asg-setup-step-node.yaml
v0/template.json
v0/template/template_config.yaml
v1/pipeline.json
v1/pipeline/stages/cd/execution-wrapper-config.yaml
v1/pipeline/steps/cd/asg-phased-deploy-step-info.yaml
v1/pipeline/steps/cd/asg-phased-deploy-step-node.yaml
v1/pipeline/steps/cd/asg-rollback-step-info.yaml
v1/pipeline/steps/cd/asg-rollback-step-node.yaml
v1/pipeline/steps/cd/asg-setup-step-info.yaml
v1/pipeline/steps/cd/asg-setup-step-node.yaml
v1/template.json
v1/template/template_config.yaml

Static Schema changes to support 3 new ASG Steps - ASG Phased Deploy, ASG Setup & ASG Rollback

[feat]: [CDS-92387]: Static Schema Changes for ASG Phased Deployment Feature

---

v0/pipeline.json
v0/pipeline/steps/cd/asg-rolling-deploy-step-info.yaml
v0/pipeline/steps/cd/asg-setup-step-info.yaml
v0/template.json
v1/examples/inputs/sample-pipeline-schema.json
v1/pipeline.json
v1/pipeline/steps/cd/asg-rolling-deploy-step-info.yaml
v1/pipeline/steps/cd/asg-setup-step-info.yaml
v1/template.json

1. Add support for max healthy percentage field in ASG rolling deploy step
2. Add support for expression values for resize strategy in ASG Setup Step
3. Make ASG Name, instance capacity & resize strategy as required fields in ASG Setup Step

[feat]: [CDS-91335]: Add max healthy percentage field in asg rolling deploy step and expressions support for asg resize strategy 

---

v0/pipeline.json
v0/pipeline/stages/cd/environment-group-metadata.yaml
v0/pipeline/stages/cd/environments-metadata.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/stages/cd/environment-group-metadata.yaml
v1/pipeline/stages/cd/environments-metadata.yaml
v1/template.json

Add expression support for parallel field in environment metadata

[feat]: [CDS-93337]: Add expression support for parallel field in environment metadata

---

v0/pipeline.json
v0/pipeline/steps/cd/k8s-patch-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/k8s-patch-step-info.yaml
v1/template.json

adding wait for steady state check

[feat]: [CDS-93024] : adding wait for steadystateCheck in the schema

---

v0/pipeline.json
v0/pipeline/stages/ci/execution-wrapper-config.yaml
v0/pipeline/steps/ci/run-test-step-v2-info.yaml
v0/pipeline/steps/ci/run-test-step-v2-node.yaml
v0/template.json

generated Pipeline and template json schema to support RuntestV2 step,
tested existing run Step by saving in pipeline, template, step template inside stage template, step groups etc.
Existing flow will not break.

[feat]: [CI-11654]: Add schema for RuntestV2

---

v0/pipeline.json
v0/pipeline/steps/cd/k8s-patch-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/k8s-patch-step-info.yaml
v1/template.json

modifying regex to support expressions for boolean
before
after

[feat]: [CDS-93024] : changing regex to incorporate function expressions for boolean values

---

v0/pipeline.json
v0/pipeline/stages/custom/execution-wrapper-config.yaml
v0/pipeline/steps/common/dbops-apply-schema-step-info.yaml
v0/pipeline/steps/common/dbops-apply-schema-step-node.yaml
v0/template.json
v0/template/template_config.yaml
v1/pipeline.json
v1/pipeline/stages/cd/deployment-stage-spec-element-wrapper-config.yaml
v1/pipeline/stages/cd/execution-wrapper-config.yaml
v1/pipeline/stages/cf/execution-wrapper-config.yaml
v1/pipeline/stages/custom/custom-stage-spec-element-wrapper-config.yaml
v1/pipeline/steps/common/dbops-apply-schema-step-info.yaml
v1/pipeline/steps/common/dbops-apply-schema-step-node.yaml
v1/template.json
v1/template/template_config.yaml

Add Apply Schema step for DB Devops Module
This is a containerised step

[feat]: [CDS-95901]: Add DB Devops Apply Schema Step

---

v0/pipeline.json
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/pipeline/steps/cd/k8s-rollout-step-command-flag.yaml
v0/pipeline/steps/cd/k8s-rollout-step-info.yaml
v0/pipeline/steps/cd/k8s-rollout-step-node.yaml
v0/pipeline/steps/cd/rollout-manifest-path-spec.yaml
v0/pipeline/steps/cd/rollout-resource-name-spec.yaml
v0/pipeline/steps/cd/rollout-resources-base-spec.yaml
v0/pipeline/steps/cd/rollout-resources-wrapper.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/stages/cd/execution-wrapper-config.yaml
v1/pipeline/steps/cd/k8s-rollout-step-command-flag.yaml
v1/pipeline/steps/cd/k8s-rollout-step-info.yaml
v1/pipeline/steps/cd/k8s-rollout-step-node.yaml
v1/pipeline/steps/cd/rollout-manifest-path-spec.yaml
v1/pipeline/steps/cd/rollout-resource-name-spec.yaml
v1/pipeline/steps/cd/rollout-resources-base-spec.yaml
v1/pipeline/steps/cd/rollout-resources-wrapper.yaml
v1/template.json

feat: [CDS-94956]: Schema changes for Rollout Step

---

v0/pipeline.json
v0/pipeline/steps/ci/docker-step-info.yaml
v0/pipeline/steps/ci/garstep-info.yaml
v0/pipeline/steps/ci/gcrstep-info.yaml
v0/template.json

Adding base image connector schema support for all build and push steps.
https://harness.atlassian.net/browse/CI-11719

feat:[CI-11719]:add base image connector schema support for all push step

---

v0/pipeline.json
v0/pipeline/stages/approval/execution-wrapper-config.yaml
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/pipeline/stages/cf/execution-wrapper-config.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/stages/approval/approval-stage-wrapper-config.yaml
v1/pipeline/stages/cf/execution-wrapper-config.yaml
v1/template.json

Include DBSchemaApply and DBSchemaRollback steps in CD, Custom and Approval stages. 
In V0:
- removing steps from CF stage
- Adding to CD and Approval stage
In V1:
- removing steps from CF stage
- Adding to Approval stage

[feat]: [DBOPS-248]: Include DBSchemaApply and DBSchemaRollback steps in CD stage

---

v0/pipeline.json
v0/pipeline/steps/common/wiz-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/common/wiz-step-info.yaml
v1/template.json

Adding IAC enum value as an option in the scan configuration

feat: [STO-7329]: Add Wiz IAC  Scan Configurations in enum

---

v0/pipeline.json
v0/pipeline/stages/ci/execution-wrapper-config.yaml
v0/pipeline/stages/security/execution-wrapper-config.yaml
v0/pipeline/steps/common/ssca-compliance-step-info.yaml
v0/pipeline/steps/common/ssca-compliance-step-node.yaml
v0/pipeline/steps/custom/repository-ssca-compliance-source.yaml
v0/pipeline/steps/custom/ssca-compliance-source-spec.yaml
v0/pipeline/steps/custom/ssca-compliance-source.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/stages/security/execution-wrapper-config.yaml
v1/pipeline/steps/common/ssca-compliance-step-info.yaml
v1/pipeline/steps/common/ssca-compliance-step-node.yaml
v1/pipeline/steps/custom/repository-ssca-compliance-source.yaml
v1/pipeline/steps/custom/ssca-compliance-source-spec.yaml
v1/pipeline/steps/custom/ssca-compliance-source.yaml
v1/template.json

Addition of SSCA Compliance step to security and ci stage
Dev testing has been done for this, the resultant yaml:
```
steps:
- step:
type: SscaCompliance
name: SscaCompliance_Step
identifier: SscaCompliance_1
spec:
source:
type: scm
spec:
connector: foobar
repoName: foobar
scan_org: false
resources:
limits:
memory: 500Mi
cpu: "0.5"
```

feat: [SSCA-1861]: SSCA Compliance Step

---

v0/pipeline.json
v0/pipeline/pipeline.yaml

Reverts harness/harness-schema#393

Revert "fix: [PIPE-16799]: Able to save Pipeline without any stage and step"

---

v0/pipeline.json
v0/pipeline/steps/cd/aws-sam-build-step-info.yaml
v0/pipeline/steps/cd/aws-sam-deploy-step-info.yaml
v0/pipeline/steps/cd/serverless-aws-lambda-deploy-v2-step-info.yaml
v0/pipeline/steps/cd/serverless-aws-lambda-package-v2-step-info.yaml
v0/pipeline/steps/cd/serverless-aws-lambda-prepare-rollback-v2-step-info.yaml
v0/pipeline/steps/cd/serverless-aws-lambda-rollback-v2-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/aws-sam-build-step-info.yaml
v1/pipeline/steps/cd/aws-sam-deploy-step-info.yaml
v1/pipeline/steps/cd/serverless-aws-lambda-deploy-v2-step-info.yaml
v1/pipeline/steps/cd/serverless-aws-lambda-package-v2-step-info.yaml
v1/pipeline/steps/cd/serverless-aws-lambda-prepare-rollback-v2-step-info.yaml
v1/pipeline/steps/cd/serverless-aws-lambda-rollback-v2-step-info.yaml
v1/template.json

Schema changes for pre execute command field in Serverless and SAM Steps. We have added this field to provide a way for the customer to install their dependencies before the execution logic kicks in
For more details , please refer to :
https://harness.atlassian.net/wiki/spaces/DEV/pages/21766963233/Tech+Spec+for+Multiple+Runtime+Support+for+Serverless+V2
Testing:
https://github.com/harness/harness-schema/assets/100153994/cf90204c-4bb6-4f01-a91b-6f783fe112ac

feat:[CDS-98715]: Schema changes for pre execute command field in Serverless and SAM Steps

---

v0/pipeline.json
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/pipeline/steps/cd/gitops-get-app-details-step-info.yaml
v0/pipeline/steps/cd/gitops-get-app-details-step-node.yaml
v0/template.json
v0/template/template_config.yaml
v1/pipeline.json
v1/pipeline/findMissingFiles.sh
v1/pipeline/stages/cd/execution-wrapper-config.yaml
v1/pipeline/steps/cd/gitops-get-app-details-step-info.yaml
v1/pipeline/steps/cd/gitops-get-app-details-step-node.yaml
v1/template.json
v1/template/template_config.yaml

Schema changes for Gitops Get App Details step
Yaml -

feat: [CDS-98406]: Gitops Get App Details Step schema changes

---

.gitignore
v0/pipeline.json
v0/pipeline/steps/common/snyk-step-info.yaml
v0/template.json

add config names for snyk step

feat: [STO-7777]: add config names for snyk step

---

Readme.md

Updated Release and Testing process in Doc

Updated Release and Testing process in Doc

---

v0/pipeline.json
v0/pipeline/stages/iacm/execution-wrapper-config.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/stages/iacm/execution-wrapper-config.yaml
v1/template.json

add snyk step to iac execution wrapper

feat: [STO-7777]: add snyk step to iac execution wrapper

---

v0/pipeline.json
v0/pipeline/steps/cd/k8s-istio-provider-spec.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/k8s-istio-provider-spec.yaml
v1/template.json

Edit Schema Changes for support for delegate virtual service in Traffic routing
in this, we are adding a boolean field in IstioProviderSpec 
and when it is marked as true we will not populate the host

feat: [CDS-99919]: Schema changes for support for delegate virtual service in Traffic routing

---

v0/pipeline.json
v0/pipeline/pipeline.yaml
v0/template.json
v0/template/pipeline/pipeline_spec.yaml

Updating schemas for newly added fixedInputsOnRerun yaml field in pipeline and pipeline template schema

feat: [PIPE-21477]: Updating schemas for newly added fixedInputsOnRerun yaml field

---

v0/pipeline.json
v0/pipeline/steps/iacm/iacmopentofu-plugin-info.yaml
v0/pipeline/steps/iacm/iacmterraform-plugin-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/iacm/iacmopentofu-plugin-info.yaml
v1/pipeline/steps/iacm/iacmterraform-plugin-info.yaml
v1/template.json

Add target, replace, and backend properties into TerraformPlugin and OpenTofuPlugin steps.
All of them should be an array of strings

feat: [IAC-2505] Add custom args into static schema

---

v0/pipeline.json
v0/pipeline/stages/approval/execution-wrapper-config.yaml
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/pipeline/stages/custom/execution-wrapper-config.yaml
v0/pipeline/steps/common/dbops-liquibase-command-step-info.yaml
v0/pipeline/steps/common/dbops-liquibase-command-step-node.yaml
v0/template.json
v0/template/template_config.yaml

LiquibaseCommand step static yaml schema
``` yaml
- step:
name: Run Liquibase Command
type: LiquibaseCommandStep
spec:
schema: myschema
instance: myinstance
command: <..> ( eg. tag / update-one-sql )
settings:
setting_name: setting_value
```

feat: [DBOPS-592]: LiquibaseCommandStep

---

v0/pipeline.json
v0/pipeline/stages/cd/azure-function-deployment-meta-data.yaml
v0/pipeline/stages/cd/azure-function-infrastructure.yaml
v0/pipeline/stages/cd/azure-function-service-spec.yaml
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/pipeline/stages/cf/execution-wrapper-config.yaml
v0/pipeline/stages/custom/execution-wrapper-config.yaml
v0/pipeline/steps/cd/azure-function-deploy-step-info.yaml
v0/pipeline/steps/cd/azure-function-deploy-step-node.yaml
v0/pipeline/steps/cd/azure-function-rollback-step-info.yaml
v0/pipeline/steps/cd/azure-function-rollback-step-node.yaml
v0/template.json
v0/template/template_config.yaml
v1/pipeline.json
v1/pipeline/stages/cd/azure-function-deployment-meta-data.yaml
v1/pipeline/stages/cd/azure-function-infrastructure.yaml
v1/pipeline/stages/cd/azure-function-service-spec.yaml
v1/pipeline/stages/cd/execution-wrapper-config.yaml
v1/pipeline/stages/cf/execution-wrapper-config.yaml
v1/pipeline/steps/cd/azure-function-deploy-step-info.yaml
v1/pipeline/steps/cd/azure-function-deploy-step-node.yaml
v1/pipeline/steps/cd/azure-function-rollback-step-info.yaml
v1/pipeline/steps/cd/azure-function-rollback-step-node.yaml
v1/template.json
v1/template/template_config.yaml

-  adding schema changes for Azure Function Deployment swimlane.

feat:[CDS-100090]: adding azure function schema

---

v0/pipeline.json
v0/pipeline/stages/approval/execution-wrapper-config.yaml
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/pipeline/stages/custom/execution-wrapper-config.yaml
v0/pipeline/steps/common/files-upload-step-info.yaml
v0/pipeline/steps/common/files-upload-step-node.yaml
v0/template.json
v1/pipeline.json
v1/template.json

We decided to override the config and merge it to develop. The azure fix can be taken up in a separate branch

New schema for the upload step

---

v0/pipeline.json
v0/pipeline/stages/cd/deployment-stage-config.yaml
v0/pipeline/stages/cd/infrastructure-def.yaml
v0/pipeline/stages/cd/service-definition.yaml
v0/template.json
v0/template/template_config.yaml

Adding schema for Azure function

feat:[CDS-100090]: New schema for the azure function step

---

v0/pipeline.json
v0/pipeline/steps/cd/azure-function-deploy-step-info.yaml
v0/pipeline/steps/cd/azure-function-rollback-step-info.yaml
v0/template.json

Fixing schema for azure function

fix:[CDS]-100090-fix-schema-for-azure-function

---

Readme.md

* This is the update to readme.

fix:[CDS-100090]: Readme update

---

v0/pipeline.json
v0/pipeline/stages/cd/multi-deployment-config.yaml
v0/template.json

fix: [CDS-103263]: Add when condition to multi deployment config

---

v0/pipeline.json
v0/pipeline/steps/cd/merge-pr-step-info.yaml
v0/pipeline/steps/cd/revert-pr-step-info.yaml
v0/pipeline/steps/cd/update-release-repo-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/merge-pr-step-info.yaml
v1/pipeline/steps/cd/revert-pr-step-info.yaml
v1/pipeline/steps/cd/update-release-repo-step-info.yaml
v1/template.json

Add option to skip git restraint on GitOps PR pipeline steps
Add disableGitRestraint to UpdateReleaseRepo step, RevertPR step, Merge step
disableGitRestraint:
oneOf:
- type: boolean
- type: string
pattern: (<\+.+>.*)
minLength: 1

feat: [CDS-101882]: Add option to skip git restraint on GitOps PR pipeline steps

---

v0/pipeline.json
v0/pipeline/steps/common/dbops-liquibase-command-step-info.yaml
v0/template.json

option for whether or not to pass changelog file to the liquibase command step

feat: [DBOPS-771]: option for whether or not to pass changelog file to the liquibase command step

---

v0/pipeline.json
v0/pipeline/steps/cd/git-ops-application-source.yaml
v0/pipeline/steps/cd/update-git-ops-app-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/git-ops-application-source.yaml
v1/pipeline/steps/cd/update-git-ops-app-step-info.yaml
v1/template.json

Adding support for updating multisource applications in gitops.

feat: [CDS-103317]: Enable update for multi-source GitOps applications

---

v0/pipeline.json
v0/pipeline/steps/cd/update-git-ops-app-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/update-git-ops-app-step-info.yaml
v1/template.json

Currently, when application is input field, UI sets all the possible fields as inputs, although some of the fields are mutually exclusive which is stated in schema, to temporary avoid clash between ui and schema we will disable validation.

fix: [CDS-103317]: Reverting validation temporary.

---

v0/pipeline.json
v0/pipeline/steps/cd/k8s-traffic-routing-destination.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/k8s-traffic-routing-destination.yaml
v1/template.json

Adding Schema changes for Port support in the destination of virtual service
yaml

feat: [CDS-104777]: Adding Schema changes for  Port support in destination of virtual service

---

v0/pipeline.json
v0/pipeline/steps/common/provenance-har-source-spec.yaml
v0/pipeline/steps/common/provenance-source.yaml
v0/pipeline/steps/common/provenance-step-info.yaml
v0/pipeline/steps/common/slsa-har-source-spec.yaml
v0/pipeline/steps/common/slsa-verification-source.yaml
v0/template.json

Update SLSA Step schema for Harness Artifact Registry
Validation : 
<video autoplay loop muted playsinline>
<source src="https://github.com/user-attachments/assets/b9f05d5a-225b-46ae-8ba7-b0a72e57d945" type="video/mp4">
Your browser does not support the video tag.
</video>

feat: [AH-737]: Update SLSA Step schema for Harness Artifact Registry

---

v0/pipeline.json
v0/pipeline/steps/common/artifact-verification-step-info.yaml
v0/pipeline/steps/common/provenance-har-source-spec.yaml
v0/pipeline/steps/common/slsa-har-source-spec.yaml
v0/template.json

Added Digest & Tag Field for HAR

feat: [AH-737]: Added Digest & Tag Field for HAR

---

v0/trigger.json
v0/trigger/trigger_type/webhook_trigger.yaml
v0/trigger/webhook_trigger/har_artifact_spec.yaml
v0/trigger/webhook_trigger/har_event_spec.yaml
v0/trigger/webhook_trigger/harness_artifact_registry_spec.yaml

feat: [AH-396]: add Harness Artifact Registry trigger schema
[AH-396]: https://harness.atlassian.net/browse/AH-396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [AH-396]: add Harness Artifact Registry trigger schema

---

v0/pipeline.json
v0/pipeline/steps/custom/email-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/custom/email-step-info.yaml
v1/template.json

Schema Changes: Adding Input Variables support for Email step
Yaml of Email step will look like this
- step:
type: Email
name: Email_1
identifier: Email_1
spec:
to: naman.talaycha@harness.io
cc: ""
subject: test
body: test  <+spec.inputVariables.test>
inputVariables:
- name: test
type: String
value: test value
timeout: 10m

feat: [CDS-105543]: Schema Changes: Adding Input Variables support for Email step

---

v0/pipeline.json
v0/pipeline/stages/approval/execution-wrapper-config.yaml
v0/pipeline/stages/approval/insert-step-node.yaml
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/pipeline/stages/cd/insert-step-node.yaml
v0/pipeline/stages/cf/execution-wrapper-config.yaml
v0/pipeline/stages/cf/insert-step-node.yaml
v0/pipeline/stages/ci/execution-wrapper-config.yaml
v0/pipeline/stages/ci/insert-step-node.yaml
v0/pipeline/stages/custom/execution-wrapper-config.yaml
v0/pipeline/stages/custom/insert-step-node.yaml
v0/pipeline/stages/iacm/execution-wrapper-config.yaml
v0/pipeline/stages/iacm/insert-step-node.yaml
v0/pipeline/stages/idp/execution-wrapper-config.yaml
v0/pipeline/stages/idp/insert-step-node.yaml
v0/pipeline/stages/insert/insert-stage-node.yaml
v0/pipeline/stages/security/execution-wrapper-config.yaml
v0/pipeline/stages/security/insert-step-node.yaml
v0/pipeline/stages/stages.yaml
v0/template.json

Schema Support for Insert Stages/Steps
Tests done ->
* Verified schema validation for insert stages on Pipeline and Template Save
* Verified schema validation for insert steps on Pipeline and Template Save

feat: [PIPE-24392]: Schema support for Insert steps and stages

---

v0/pipeline.json
v0/pipeline/steps/common/provenance-har-source-spec.yaml
v0/pipeline/steps/common/slsa-har-source-spec.yaml
v0/template.json

Added Property Fields for Digest & Tag Field for HAR

fix: [AH-737]: Added Property for Digest & Tag Field for HAR

---

v0/pipeline.json
v0/pipeline/stages/approval/execution-wrapper-config.yaml
v0/pipeline/stages/cf/execution-wrapper-config.yaml
v0/pipeline/stages/ci/execution-wrapper-config.yaml
v0/pipeline/stages/custom/execution-wrapper-config.yaml
v0/template.json

Register event listener step to approval, custom, ci and cf stage

feat: [CDS-105905]: Register event listener step

---

v0/template.json
v0/template/notification/notification_template_body.yaml

changed the type from String to STRING

Made type a enum field

---

v0/pipeline.json
v0/pipeline/stages/ci/buildIntelligence.yaml
v0/pipeline/stages/ci/caching.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/stages/ci/buildIntelligence.yaml
v1/pipeline/stages/ci/caching.yaml
v1/template.json

we have CI and BI in our overview page as boolean, but customer wants to enable them based on conditions.
**Testing:**

fix: [CI-15706]: added support of conditional execution for both BI  and CI

---

v0/pipeline.json
v0/pipeline/stages/security/execution-wrapper-config.yaml
v0/template.json

This pull request introduces a new verification step, `SlsaVerificationStepNode`, to the pipeline configuration files. The most important changes include updates to multiple JSON and YAML files to incorporate this new step.
* [`v0/pipeline.json`](diffhunk://#diff-47707a8e6ec1ce8b8accc4042a2a481d7326e615194d86699b01aa0c5d8abab2R8459-R8460): Added `SlsaVerificationStepNode` to the list of pipeline steps.
* [`v0/pipeline/stages/security/execution-wrapper-config.yaml`](diffhunk://#diff-25961101f4ae1230fe0558c70c7cf9c0fc89daa604a801c1fdb997922c05978fR71): Included `slsa-verification-step-node.yaml` in the execution wrapper configuration.
* [`v0/template.json`](diffhunk://#diff-6c0f24251df68b230837bfd880ada4985d7b2b49d80929c20bfa14bac2c7673cR86368-R86369): Added `SlsaVerificationStepNode` to …

feat:[SSCA-3391]: Add SLSA verification to the Security stage

---

v0/pipeline.json
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/pipeline/stages/custom/execution-wrapper-config.yaml
v0/pipeline/steps/cd/helm-delete-step-info.yaml
v0/pipeline/steps/cd/helm-delete-step-node.yaml
v0/template.json
v0/template/template_config.yaml
v1/pipeline.json
v1/pipeline/stages/cd/execution-wrapper-config.yaml
v1/pipeline/steps/cd/helm-delete-step-info.yaml
v1/pipeline/steps/cd/helm-delete-step-node.yaml
v1/template.json

- Added definition for Helm Delete step.
- It can be used on CD and Custom stages.
- Also supported on template studio.

feat: [CDS-106587]: Added helm delete step definition

---

v0/trigger.json
v0/trigger/webhook_trigger/github_create_spec.yaml
v1/trigger.json
v1/trigger/webhook_trigger/github_create_spec.yaml

Context - https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/module/code/orgs/HarnessHCRInternalUAT/projects/Harness_Code/repos/harness-core/pulls/72229

[feat]: [CDS-106832]: Schema changes for Github Create Event

---

v0/trigger.json
v0/trigger/webhook_trigger/gitlab_tag_spec.yaml
v1/trigger.json
v1/trigger/webhook_trigger/gitlab_tag_spec.yaml

Context - https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/module/code/orgs/HarnessHCRInternalUAT/projects/Harness_Code/repos/harness-core/pulls/72254/changes

[feat]: [CDS-106871]: Schema changes for Tag Event for Gitlab Triggers

---

v0/pipeline.json
v0/pipeline/steps/cd/k8s-delete-step-command-flag.yaml
v0/pipeline/steps/cd/k8s-delete-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/k8s-delete-step-command-flag.yaml
v1/pipeline/steps/cd/k8s-delete-step-info.yaml
v1/template.json

**Tech Spec**
- https://harness.atlassian.net/browse/CDS-106966
**Feature**
- https://harness.atlassian.net/browse/CDS-106964

feat:[CDS-107111]: Added commandFlags field to k8s delete step

---

v0/trigger.json
v0/trigger/webhook_trigger/har_artifact_spec.yaml

feat: [AH-1116] remove artifact modification action 
[AH-1116]: https://harness.atlassian.net/browse/AH-1116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [AH-1116]: remove artifact modification action

---

v0/pipeline.json
v0/pipeline/build.yaml
v0/template.json
v1/pipeline/build.yaml

feat: [CI-13445]: update schema for supporting commitSha in git clone

---

v0/pipeline.json
v0/pipeline/steps/cd/terraform-cloud-plan-spec.yaml
v0/template.json

feat: [CDS-108495]: add refresh comand type for plan run-type for terraform cloud

---

v0/pipeline.json
v0/pipeline/stages/approval/insert-step-node.yaml
v0/pipeline/stages/cd/insert-step-node.yaml
v0/pipeline/stages/cf/insert-step-node.yaml
v0/pipeline/stages/ci/insert-step-node.yaml
v0/pipeline/stages/custom/insert-step-node.yaml
v0/pipeline/stages/iacm/insert-step-node.yaml
v0/pipeline/stages/idp/insert-step-node.yaml
v0/pipeline/stages/insert/insert-stage-node.yaml
v0/pipeline/stages/security/insert-step-node.yaml
v0/template.json

Added Schema to Support "" empty string for insert steps and stages

feat: [PIPE-26743]: Schema Fix for Empty Insert steps/stages

---

v0/template.json
v0/template/template_config.yaml

Was added Helm canary, canary delete, blue/green, and swap steps to template schema.

fix:[CDS-109067]: Add missing helm steps to template schema

---

cdevents/README.md
cdevents/conformance/build_started.json
cdevents/conformance/pipelinerun_finished_failure.json
cdevents/conformance/pipelinerun_finished_success.json
cdevents/conformance/pipelinerun_started.json
cdevents/templates/build_started.json
cdevents/templates/pipelinerun_finished_failure.json
cdevents/templates/pipelinerun_finished_success.json
cdevents/templates/pipelinerun_started.json
developer-onboarding.md

Add CD events templates and examples.
Readme added for ease of implementation

feat: [PIPE-26731] Add CD events templates and examples

---

v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/pipeline/stages/custom/execution-wrapper-config.yaml
v0/pipeline/steps/cd/ai-test-automation-step-info.yaml
v0/pipeline/steps/cd/ai-test-automation-step-node.yaml
v0/template.json
v0/template/template_config.yaml
v1/pipeline/findMissingFiles.sh
v1/pipeline/stages/cd/deployment-stage-spec-element-wrapper-config.yaml
v1/pipeline/stages/cd/execution-wrapper-config.yaml
v1/pipeline/stages/custom/custom-stage-spec-element-wrapper-config.yaml
v1/pipeline/steps/cd/ai-test-automation-step-info.yaml
v1/pipeline/steps/cd/ai-test-automation-step-node.yaml
v1/template.json
v1/template/template_config.yaml

Schema added for AI Test Automation
- Tested in Devspace end to end
- 3 required inputs - TestSuiteName, EnvironmentName, ApplicationName
- Added to CD and custom stages

feat: [AI-316] Schema changes for AI Test Automation Step

---

v0/pipeline.json
v0/pipeline/steps/iacm/iacmtflint-plugin-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/iacm/iacmtflint-plugin-info.yaml
v1/template.json

Add RTI fields for iacm tf lint

[feat]: [IAC-3648]: Add runtime input fields

---

v0/pipeline.json
v0/pipeline/steps/common/stoyaml-burp-tool-data.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/common/stoyaml-burp-tool-data.yaml
v1/template.json

updates to burp tool data yaml to support detailed scopes

feat: [STO-8524]: updates to burp tool data yaml to support detailed scopes

---

v0/pipeline.json
v0/pipeline/steps/common/dbops-rollback-schema-step-info.yaml
v0/template.json

Add a changeSetCount field to the rollback schema step

feat: [DBOPS-1024]: Add changeSetCount field in rollback schema

---

v0/template.json
v0/template/workspace/template.yaml
v1/template.json
v1/template/workspace/template.yaml

This pull request introduces enhancements to template schemas (`v0` and `v1`) and aligns property naming conventions for consistency. The most significant changes include adding new optional fields (`description` and `tags`) and renaming `defaultPipelines` to `default_pipelines` for a more consistent naming convention.
* Added `description` and `tags` fields to the `spec` section in `v0/template.json` and `v1/template.json`, allowing for optional metadata in the form of a string and an array of strings, respectively. (`[[1]](diffhunk://#diff-6c0f24251df68b230837bfd880ada4985d7b2b49d80929c20bfa14bac2c7673cR1070-R1078)`, `[[2]](diffhunk://#diff-0397c2f1db0c2902bc79c0a01d74f44496e170634c80fc3894c2d04dfc2af6beR1202-R1210)`)
* Added `description` and `tags` fields to the `spec` section in …

feat: [IAC-3635]: Add tags, description and change defaultPipelines to default_pipelines

---

v0/pipeline.json
v0/pipeline/steps/common/aqua-trivy-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/common/aqua-trivy-step-info.yaml
v1/template.json

add fs to config enum in aqua trivy step yaml

feat: [STO-8939]: add fs to config enum in aqua trivy step yaml

---

v0/pipeline.json
v0/pipeline/steps/common/checkmarx-one-step-info.yaml
v0/pipeline/steps/common/stoyaml-checkmarx-tool-data.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/common/checkmarx-one-step-info.yaml
v1/pipeline/steps/common/stoyaml-checkmarx-one-tool-data.yaml
v1/template.json

Changes for new config added for cxone dast support

feat:[STO-9039]: schema changes for cxone dast

---

v0/pipeline.json
v0/pipeline/stages/iacm/execution-wrapper-config.yaml
v0/pipeline/stages/iacm/iacmstage-config-impl.yaml
v0/pipeline/steps/iacm/iacmansible-plugin-info.yaml
v0/pipeline/steps/iacm/iacmansible-plugin-step-node.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/stages/iacm/execution-wrapper-config.yaml
v1/pipeline/stages/iacm/iacmstage-config-impl.yaml
v1/pipeline/steps/iacm/iacmansible-plugin-info.yaml
v1/pipeline/steps/iacm/iacmansible-plugin-step-node.yaml
v1/template.json

Added static schema for Ansible step:
- **IACMAnsiblePluginStepNode**
- **IACMAnsiblePluginInfo**
Adjusted IACMStageNode with additional properties:
- **playbooks**
- **inventories**

feat: [IAC-4006]: static schema for Ansible step

---

v0/pipeline.json
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/template.json

Added schema changes to support S3Upload step in CD

feat: [CDS-111698]: added schema changes to support S3Upload step in CD

---

v0/pipeline.json
v0/pipeline/steps/cd/terraform-cloud-cli-plan-execution-data.yaml
v0/pipeline/steps/cd/terraform-cloud-cli-step-configuration.yaml
v0/pipeline/steps/cd/terraform-plan-execution-data.yaml
v0/pipeline/steps/cd/terraform-step-configuration.yaml
v0/template.json

[feat]:[CDS-111847]: step configuration create workspace 

---

v0/pipeline.json
v0/pipeline/codebase.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/codebase.yaml
v1/template.json

adding boolean field persistCredentials in codebase.

feat: [CI-18088]: adding field persistCredentials in codebase

---

v0/pipeline.json
v0/pipeline/common/run-mode-config.yaml
v0/pipeline/stages/approval/approval-stage-node.yaml
v0/pipeline/stages/cd/deployment-stage-node.yaml
v0/pipeline/stages/cf/feature-flag-stage-node.yaml
v0/pipeline/stages/ci/integration-stage-node.yaml
v0/pipeline/stages/custom/custom-stage-node.yaml
v0/pipeline/stages/iacm/iacmstage-node.yaml
v0/pipeline/stages/idp/idpstage-node.yaml
v0/pipeline/stages/security/security-stage-node.yaml
v0/template.json

Harness-core changes: https://harness0.harness.io/ng/account/l7B_kbSEQD2wjrM7PShm5w/module/code/orgs/PROD/projects/Harness_Commons/repos/harness-core/pulls/105326

feat:[PIPE-28606]: Schema changes to add run mode in stage yaml
