harness/harness-schema

v0/pipeline.json
v0/pipeline/pipeline.yaml
v0/pipeline/pipeline_root.yaml

Currently pipeline field is not marked as required field and hence ui breaks when once moves from yaml to visual .

feat: [CDS-0]: making pipeline and stages as required

---

v0/pipeline.json
v0/pipeline/steps/cd/serverless-aws-lambda-rollback-v2-step-info.yaml
v0/template.json

We had to changes Serverless Rollback V2 from delegate task to Container Step. So the changes for this are according to that. No customer right now, is using this swimlane

feat:[CDS-76042]: Serverless Rollback V2 Step Changes

---

v1/pipeline.json
v1/pipeline/steps/cd/aws-sam-build-step-info.yaml
v1/pipeline/steps/cd/aws-sam-deploy-step-info.yaml
v1/pipeline/steps/cd/serverless-aws-lambda-deploy-v2-step-info.yaml
v1/pipeline/steps/cd/serverless-aws-lambda-package-v2-step-info.yaml
v1/pipeline/steps/cd/serverless-aws-lambda-prepare-rollback-v2-step-info.yaml
v1/pipeline/steps/cd/serverless-aws-lambda-rollback-v2-step-info.yaml
v1/template.json

Following are the requirements -
- Remove hard requirements for AWS Manual Creds for SAM Deploy Step
- In SAM Build, if we provide docker connector with no creds we are throwing error.
- Also in this ticket we would add runtime inputs for connector ref for SAM steps
- we would add runtime inputs for connector ref for Serverless 2.0 steps
- Runtime Inputs Not currently supported for SAM stackName . Fixing it in this PR
- Runtime Inputs Not supported Sam version. . Fixing it in this PR
- Runtime Inputs Not supported Serverless 2.0 version. Fixing it in this PR

feat:[CDS-77084]: Serverless 2.0 and SAM step changes

---

v1/pipeline.json
v1/pipeline/common/empty_spec.yaml
v1/pipeline/common/failure.yaml
v1/pipeline/common/failure_action.yaml
v1/pipeline/common/failure_list.yaml
v1/pipeline/common/failure_retry.yaml
v1/pipeline/common/on.yaml
v1/pipeline/common/retry_failure.yaml
v1/pipeline/common/retry_failure_action.yaml
v1/pipeline/stages/custom/custom-stage-node.yaml
v1/pipeline/stages/stages.yaml
v1/template.json

Update failure strategies schema as per drone schema: https://github.com/drone/spec/pull/17
**Updated yaml of failure strategies:**
```
failures:
- errors:
- authorization
action:
type: abort
- errors:
- connectivity
action:
type: retry
spec:
attempts: 2
intervals:
- 10s
- 20s
failure:
action:
type: manual-intervention
spec: 
timeout: 10m
timeout_action: 
type: success
- errors:
- all
action:
type: manual-intervention
spec: 
timeout_action:
type: ignore
timeout: 10m
```
**older yaml:**
```
on:
failure:
- errors:
- all
type: retry
spec: 
attempts: 2
interval: 10m
spec:
post_action:
type: abort
```

feat: [CDS-78628]: update failure strategies schema

---

v0/pipeline.json
v0/pipeline/steps/common/aws-cdk-deploy-step-info.yaml
v0/pipeline/steps/common/aws-cdk-destroy-step-info.yaml
v0/pipeline/steps/common/aws-cdk-diff-step-info.yaml
v0/pipeline/steps/common/aws-cdk-synth-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/common/aws-cdk-deploy-step-info.yaml
v1/pipeline/steps/common/aws-cdk-destroy-step-info.yaml
v1/pipeline/steps/common/aws-cdk-diff-step-info.yaml
v1/pipeline/steps/common/aws-cdk-synth-step-info.yaml
v1/template.json

fix: [CDS-80869]: support runtime input for stacknames
[CDS-80869]: https://harness.atlassian.net/browse/CDS-80869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [CDS-80869]: support runtime input for stacknames

---

v0/pipeline.json
v0/pipeline/steps/common/ssca-enforcement-step-info.yaml
v0/pipeline/steps/custom/cd-ssca-enforcement-step-info.yaml
v0/pipeline/steps/custom/enforcement-policy.yaml
v0/pipeline/steps/custom/ssca-opa-policy-config.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/custom/cd-ssca-enforcement-step-info.yaml
v1/pipeline/steps/custom/enforcement-policy.yaml
v1/pipeline/steps/custom/ssca-opa-policy-config.yaml
v1/template.json

**Existing schema**
policy:
store:
type: Harness
spec:
file: /valid_policy_file_for_at
resources:
**New schema**
> with policy object
policy:
store:
type: Harness
spec:
file: /valid_policy_file_for_at
resources:
> with policySet object
policy:
policySet: <scopedPolicySetRef>   
resources:

feat: [SSCA-1004]: Updating the ssca enforcement schema to use either the policy object or the policySet object

---

v0/pipeline.json
v0/pipeline/steps/cd/k8s-apply-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/k8s-apply-step-info.yaml
v1/template.json

Description:
Adding logic to not allow user to save when providing both filepaths and manifestSource for K8sApplyStep. Previously added this logic in core repository which used to work on local and devspace but is not working on QA. 
Testing:
1. did local testing by using generated pipeline.json in harness-core, 
When filepath and manifest source both are provided
2. when only one exists

[fix]: [CDS-85889] : add oneof logic in between filepaths and manifest source for Apply Step

---

v1/examples/failure_strategies/group.yaml
v1/examples/failure_strategies/stage.yaml
v1/examples/failure_strategies/step.yaml
v1/examples/parallel/group.yaml
v1/examples/parallel/stages.yaml
v1/examples/parallel/steps.yaml
v1/examples/pipeline/pipeline_with_options.yaml
v1/examples/templates/pipeline.yaml
v1/examples/when/group.yaml
v1/examples/when/stage.yaml
v1/examples/when/step.yaml
v1/pipeline.json
v1/pipeline/stages/custom/custom-stage-spec-element-config.yaml
v1/template.json

Removing input_vars: [] and output_vars: [] from http step examples for v1 because these fields are required to be of type   object in v1

fix examples

---

v0/pipeline.json
v0/pipeline/steps/cd/ecs-blue-green-create-service-step-info.yaml
v0/pipeline/steps/cd/ecs-rolling-deploy-step-info.yaml
v0/pipeline/steps/cd/ecs-service-setup-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/ecs-blue-green-create-service-step-info.yaml
v1/pipeline/steps/cd/ecs-rolling-deploy-step-info.yaml
v1/pipeline/steps/cd/ecs-service-setup-step-info.yaml
v1/template.json

Description:
Added support for expressions for fields in ECS steps
Testing:
1. validating by saving ECS Pipeline with BG Create Service steps and all boolean fields as expressions.
2. validating by saving ECS Pipeline with BG Create Service steps and all boolean fields as runtime inputs.
3. validating by saving ECS Pipeline with BG Create Service steps and all boolean fields as fixed values.

[fix]: [CDS-80821]: added support for expressions for fields in ECS steps

---

v0/pipeline.json
v0/pipeline/steps/cd/azure-repo-store.yaml
v0/pipeline/steps/cd/bitbucket-store.yaml
v0/pipeline/steps/cd/git-lab-store.yaml
v0/pipeline/steps/cd/git-store.yaml
v0/pipeline/steps/cd/github-store.yaml
v0/pipeline/steps/cd/helm-chart-manifest.yaml
v0/pipeline/steps/cd/inherit-from-manifest-store-config.yaml
v0/pipeline/steps/cd/k8s-manifest.yaml
v0/pipeline/steps/cd/kustomize-manifest.yaml
v0/pipeline/steps/cd/openshift-manifest.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/azure-repo-store.yaml
v1/pipeline/steps/cd/bitbucket-store.yaml
v1/pipeline/steps/cd/git-lab-store.yaml
v1/pipeline/steps/cd/git-store.yaml
v1/pipeline/steps/cd/github-store.yaml
v1/pipeline/steps/cd/helm-chart-manifest.yaml
v1/pipeline/steps/cd/inherit-from-manifest-store-config.yaml
v1/pipeline/steps/cd/k8s-manifest.yaml
v1/pipeline/steps/cd/kustomize-manifest.yaml
v1/pipeline/steps/cd/openshift-manifest.yaml
v1/template.json

As part of this PR we want remove limit on user not being able to provide expression for K8s related manifests. Before only valid values were actual array list or `<+input>` expression.

fix: [CDS-86705]: Allow expressions as input for paths field

---

v0/pipeline.json
v0/pipeline/stages/cd/aws-instance-filter.yaml
v0/pipeline/stages/cd/ssh-win-rm-aws-infrastructure.yaml
v0/template.json
v1/pipeline/stages/cd/aws-instance-filter.yaml
v1/pipeline/stages/cd/ssh-win-rm-aws-infrastructure.yaml

updated schema for ssh aws infra with Vpcs and AsgName 
With filter:
```
infrastructureDefinition:
name: pdcAws
identifier: pdcAws
orgIdentifier: default
projectIdentifier: vitalie
environmentRef: ssh
deploymentType: Ssh
type: SshWinRmAws
spec:
credentialsRef: account.vit2CdPlay
connectorRef: account.awsCdplay
region: us-east-1
awsInstanceFilter:
tags:
vit: "true"
Name: vitasg
vpcs:
- vpc-0c5b9086ccea05263xx
hostConnectionType: PublicIP
allowSimultaneousDeployments: false
```
With ASG
```
infrastructureDefinition:
name: pdcAws2
identifier: pdcAws2
orgIdentifier: default
projectIdentifier: vitalie
environmentRef: ssh
deploymentType: Ssh
type: SshWinRmAws
spec:
credentialsRef: account.vit2CdPlay
connectorRef: account.awsCdplay
region: us-east-1
asgName: myAsg
hostConnectionType: PublicIP …
```

feat: [CDS-87189]: updated schema for ssh aws infra

---

v0/pipeline/pms-webhook-channel.yaml

feat: [CDS-80231]: adds header support in custom webhook notification method
Change: Adds headers as map (object here) under PmsWebhookChannel schema.
[CDS-80231]: https://harness.atlassian.net/browse/CDS-80231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [CDS-80231]: adds header support in custom webhook notification method

---

v1/examples/cd_entities/environment-entity.yaml
v1/examples/cd_entities/infra-def-entity.yaml
v1/examples/cd_entities/service-entity.yaml
v1/examples/pipeline/stages/cd/service_env_variations/env-with-deploy-all-filter.yaml
v1/examples/pipeline/stages/cd/service_env_variations/env-with-tag-filters.yaml
v1/examples/pipeline/stages/cd/service_env_variations/inherit-service-env.yaml
v1/examples/pipeline/stages/cd/service_env_variations/multi-service-env.yaml
v1/examples/pipeline/stages/cd/service_env_variations/runitme-infra.yaml
v1/examples/pipeline/stages/cd/service_env_variations/runtime-service-env.yaml
v1/examples/pipeline/stages/cd/service_env_variations/single-service-env.yaml
v1/pipeline.json
v1/pipeline/stages/cd/deployment-stage-config.yaml
v1/pipeline/stages/cd/env-infra-filter-yaml.yaml
v1/pipeline/stages/cd/environment-group-yaml.yaml
v1/pipeline/stages/cd/environment-yaml-v2.yaml
v1/pipeline/stages/cd/environment-yaml.yaml
v1/pipeline/stages/cd/environments-yaml.yaml
v1/pipeline/stages/cd/filter-yaml.yaml
v1/pipeline/stages/cd/infra-structure-definition-yaml.yaml
v1/pipeline/stages/cd/inherit-env-with-config.yaml
v1/pipeline/stages/cd/inherit-environment.yaml
v1/pipeline/stages/cd/tags-type-filter.yaml
v1/template.json

Env config
First
```
environments:
values:
- ref: prod-3
inputs:
infra:         ##### infras - not suitable
- id: k8s-us   ##### ref vs id 
inputs: 
sequential: true   ##### replaced parallel
```
Second
```
environments:
inherit:
stage: pre-qa   
with:      ##### would be optional/ open via checkbox
- env: preqa-environment  ##### single env user need to give env again in yaml
infra: infra-us-east
inputs:
sequential: true    ##### optional
```
Third
```
environments:
filters:
envs: 
- tags:
a:b
c:d
condition: OR      ###### Optional | Default value AND
infra_defs:
- tags:
a:b
c:d
condition: AND      ###### Optional | Default value AND
sequential: true    ##### this field is not available in v0
environments:
filters:
envs: 
- tags: {}
infra_defs:
- tags:
a:b
c:d
condition: OR      ###### …
```

[feat]: [CDS-87898] : added environments yaml v1 schema

---

v0/pipeline.json
v0/pipeline/steps/custom/repository-sbom-drift.yaml
v0/pipeline/steps/custom/repository-sbom-source.yaml
v0/pipeline/steps/custom/sbom-drift-spec.yaml
v0/pipeline/steps/custom/sbom-drift.yaml
v0/pipeline/steps/custom/sbom-source.yaml
v0/template.json

New Orchestration Step Yaml
```
step:
type: SscaOrchestration
name: SscaOrchestration
identifier: SscaOrchestration
spec:
mode: generation
source:
type: image | repository #This is repository case
spec:
url: https://github.com/harness/harness-core
path: /ssca-manager
variant_type: git-branch | git-tag | commit
variant: develop
cloned_codebase: default=/harness
type: Syft
spec:
format: cyclonedx-json | spdx-json
attestation: 
type: cosign
spec:
privateKey: text_cosign_private_key
password: text_cosign_password
sbom_drift:
base: baseline | last_generated_sbom | repository  #This is custom_tag case
spec:
variant: develop
variant_type: branch
```
Changes Done:
- Adding new source type `repository` and corresponding spec.
- Adding new sbom_drift type `repository` and corresponding spec

feat: [SSCA-1245]: Added Repository Source in SSCA Orchestration Step

---

v0/pipeline.json
v0/pipeline/stages/cd/ssh-win-rm-aws-infrastructure.yaml
v0/pipeline/stages/cd/ssh-win-rm-azure-infrastructure.yaml
v0/template.json
v1/pipeline/stages/cd/ssh-win-rm-aws-infrastructure.yaml
v1/pipeline/stages/cd/ssh-win-rm-azure-infrastructure.yaml

added targetedHosts to ssh infra AWS and Azure
```
infrastructureDefinition:
name: aws-infra
identifier: awsinfra
orgIdentifier: default
projectIdentifier: alexc
environmentRef: prod
deploymentType: Ssh
type: SshWinRmAws
spec:
credentialsRef: <+input>
connectorRef: <+input>
region: <+input>
awsInstanceFilter:
tags: <+input>
vpcs: []
hostConnectionType: PublicIP
targetedHosts: <+input>
allowSimultaneousDeployments: false
```
```
infrastructureDefinition:
name: azure-infra
identifier: azureinfra
orgIdentifier: default
projectIdentifier: alexc
environmentRef: prod
deploymentType: Ssh
type: SshWinRmAzure
spec:
credentialsRef: <+input>
connectorRef: <+input>
subscriptionId: <+input>
resourceGroup: <+input>
tags: <+input>
hostConnectionType: Hostname
targetedHosts: <+input> …
```

feat: [CDS-87603]: added targetedHosts to ssh infra AWS and Azure

---

v0/pipeline/steps/cd/k8s-traffic-routing-provider-base-spec.yaml
v1/pipeline/steps/cd/k8s-traffic-routing-provider-base-spec.yaml

Added a new field for k8s traffic routing which will be used to name the traffic routing resources during creation.

[feat]: [CDS-88257]: adding k8s traffic resource name field

---

v1/pipeline.json
v1/pipeline/steps/custom/approver-input-info.yaml
v1/pipeline/steps/custom/harness-approval-step-info.yaml
v1/template.json

- approval message is not empty but not mandatory in V0 schema. We can't make it mandatory in V0, hence making it mandatory in V1. FE also mandates this field.
- similar case is with `approver input's name` field. [`FE ticket`](https://harness.atlassian.net/browse/CDS-88673) to make this field mandatory
- Additional a regex check which was missed in V1.
- Tested the changes locally

feat:[CDS-88674]: make non empty approval fields mandatory in V1

---

v0/pipeline.json
v0/pipeline/steps/cd/k8s-route-spec-base.yaml
v0/pipeline/steps/cd/k8s-route-spec-inherit.yaml
v0/pipeline/steps/cd/k8s-route-spec.yaml
v0/pipeline/steps/cd/k8s-traffic-routing-spec-inherit.yaml
v0/pipeline/steps/cd/k8s-traffic-routing-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/k8s-route-spec-base.yaml
v1/pipeline/steps/cd/k8s-route-spec-inherit.yaml
v1/pipeline/steps/cd/k8s-route-spec.yaml
v1/pipeline/steps/cd/k8s-traffic-routing-provider-base-spec.yaml
v1/pipeline/steps/cd/k8s-traffic-routing-spec-inherit.yaml
v1/pipeline/steps/cd/k8s-traffic-routing-step-info.yaml
v1/template.json

Updating k8s traffic routing schema
1. Moving destinations from global to under each of the route instances
2. Adding name field for each of the routes

[feat]: [CDS-89237]: updating k8s traffic routing schema

---

bundler/schema_store/src/main/java/io/harness/YamlEntityType.java
bundler/schema_store/src/main/java/io/harness/bundler/SchemaBundlerRegistrar.java
v1/examples/cd_entities/infra-def-entity.yaml
v1/examples/cd_entities/service-entity.yaml
v1/infra.json
v1/infraStructureEntity/infra-def-basic-spec.yaml
v1/infraStructureEntity/infra-def-entity.yaml
v1/infraStructureEntity/infra-def-spec.yaml
v1/infraStructureEntity/kubernetes-gcp-infra-def-spec.yaml

https://harness.atlassian.net/wiki/spaces/~5ce42d90c9167e0d6ea29342/pages/21583530813/Service+Environment+Yaml+Simplification#Infrastructure-Definitions
Example
```
version: 1
kind: infra-def
spec:
type: kubernetes-gcp
spec:
connector: account.k8s_gcp
cluster: prod2
namespace: default
release: release-<+INFRA_KEY_SHORT_ID>
parallel: true
variables:
tag:
type: String
value: 1.9.0```

[feat]: [CDS-91849] : added infrastructure entity schema

---

v1/examples/cd_entities/infra-def-entity.yaml
v1/examples/cd_entities/service-entity.yaml
v1/infra.json
v1/infraStructureEntity/infra-def-spec.yaml
v1/service.json
v1/serviceEntity/service-spec.yaml

infra
```
version: 1
kind: infra-def
spec:
type: kubernetes-gcp
spec:
connector: account.k8s_gcp
cluster: prod2
namespace: <+inputs.input_1>
release: release-<+INFRA_KEY_SHORT_ID>
parallel: true
variables:
tag:
type: String
value: 1.9.0
inputs:
input_1:
type: string
default: abc
```
service 
```
version: 1
kind: service
type: native-helm
spec:
variables:
tag:
type: String
value: 1.9.0
inputs:
input_1:
type: string
default: abc
```

[feat]: [CDS-91902] : adding inputs in infra and service entity schema

---

v0/pipeline.json
v0/pipeline/steps/cd/helm-values.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/helm-values.yaml
v1/template.json

Currently the `valueFiles` attribute in UpdateGitopsApp step only supports fixed values and runtime expression. This change allows the usage of expressions in this field.

fix: [CDS-95409]: allow expressions in Update Gitops App step's valueFiles

---

v0/pipeline.json
v0/pipeline/stages/custom/execution-wrapper-config.yaml
v0/pipeline/steps/common/dbops-rollback-schema-step-info.yaml
v0/pipeline/steps/common/dbops-rollback-schema-step-node.yaml
v0/template.json
v0/template/template_config.yaml
v1/pipeline.json
v1/pipeline/stages/cd/deployment-stage-spec-element-wrapper-config.yaml
v1/pipeline/stages/cd/execution-wrapper-config.yaml
v1/pipeline/stages/cf/execution-wrapper-config.yaml
v1/pipeline/stages/custom/custom-stage-spec-element-wrapper-config.yaml
v1/pipeline/steps/common/dbops-rollback-schema-step-info.yaml
v1/pipeline/steps/common/dbops-rollback-schema-step-node.yaml
v1/template.json
v1/template/template_config.yaml

Add Rollback Schema step for DB Devops Module
This is a containerised step
Example step configuration in step template:
```
template:
name: schema_rollback
identifier: schema_rollback_1
versionLabel: "1"
type: Step
projectIdentifier: NG_Trial
orgIdentifier: default
tags: {}
spec:
type: DBSchemaRollback
spec:
connectorRef: <+input>
dbInstance: ab/bc
image: drone-liquibase:latest
build: <+input>
tag: abcd
description: <+input>
```

[feat]: [DBOPS-176]: onboard DBDevOps rollback schema step

---

v0/pipeline.json
v0/pipeline/steps/common/wiz-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/common/wiz-step-info.yaml
v1/template.json

Wiz Scan Configuration Enum currently supports "Default". This PR is created to add directory and container images to the scan configuration in STO.

feat: [STO-7524]: Add Wiz Scan Configurations in enum

---

v0/pipeline.json
v0/pipeline/steps/common/dbops-apply-schema-step-info.yaml
v0/pipeline/steps/common/dbops-rollback-schema-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/common/dbops-apply-schema-step-info.yaml
v1/pipeline/steps/common/dbops-rollback-schema-step-info.yaml
v1/template.json

Update static schema for DBSchemaApply and DBSchemaRollback step to include dbSchema field.
Also: 
- Adding required check for dbSchema and dbInstance field.
- Removing minimum length for fields (May be it was introduced as we were concatening both fields in dbInstance earlier)
Example step yaml:
```
type: DBSchemaRollback
name: DBSchemaRollback
identifier: DBSchemaRollback
spec:
connectorRef: harness
dbInstance: instance
dbSchema: account.schema
image: drone-liquibase:latest
tag: abcded
timeout: 10m
```

[feat]: [DBOPS-176]: Update static schema for DBSchemaApply and DBSchemaRollback step

---

v0/pipeline.json
v0/pipeline/steps/custom/repository-ssca-compliance-source.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/custom/repository-ssca-compliance-source.yaml
v1/template.json

SSCA Compliance step does not accept expression in scan_org field. To fix this added OneOf boolean or string with pattern.
The same is done for the privilege variable in pipeline.

feat: [SSCA-1954]: Allowed expressions in Ssca Compliance scan_org field

---

v0/pipeline.json
v0/pipeline/pipeline.yaml

Ticket Link: https://harness.atlassian.net/browse/PIPE-16799
Issue: Customer could save pipeline without any stages and step
Changes: Making "stages" in the yaml as required field.
Testing: Done in local
- Tested changes after updating pipeline.json 
- To ensure requirement of stages for a pipeline, checked template flow as well.
- Ensured we get proper error message when we try to create a stage or pipeline template without any stage.
Screenshots:

fix: [PIPE-16799]: Able to save Pipeline without any stage and step

---

v0/pipeline.json
v0/pipeline/steps/custom/repository-ssca-compliance-source.yaml
v0/template.json

We want to have this field as both expression and runtime input.

feat: [SSCA-2017]: allow scan org expression via harness schema

---

v1/pipeline/steps/common/report.yaml

Added a strict string validation for report path to contain either an array or runtime-input

fix: [CI-12730]: added pattern for report path in steps

---

v0/pipeline.json
v0/pipeline/steps/cd/helm-deploy-step-info.yaml
v0/pipeline/steps/cd/helm-rollback-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/helm-deploy-step-info.yaml
v1/pipeline/steps/cd/helm-rollback-step-info.yaml
v1/template.json

Allow environment variables field for native helm steps. The values can be either runtime input or map of string key and values
| Test Case | Screenshot |
|--------|--------|
| Helm Deployment Step with environment variables and multiple value types (expression, fixed and runtime) | <img width="371" alt="Screenshot 2024-06-14 at 14 59 03" src="https://github.com/harness/harness-schema/assets/64782481/639ff5a2-3ef0-4ace-8c99-7a1e80fb548a"> |
| Helm Rollback step with environment variables as runtime input | <img width="321" alt="Screenshot 2024-06-14 at 14 59 14" src="https://github.com/harness/harness-schema/assets/64782481/91a64720-7a5b-4ffd-8078-1ccace04a7d0"> |
| Runtime input screen for case 1 and 2 | <img width="354" alt="Screenshot 2024-06-14 at 14 59 24" …

feat: [CDS-97667]: Add environment variables schema for native helm step

---

v0/pipeline.json
v0/pipeline/steps/cd/sync-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/sync-step-info.yaml
v1/template.json

This will add a new property to gitops sync step. **applicationRegex**
This should be a regex string(validated in code with pattern.compile())
And with this change, only one of either applicationList(existing field) or applicationRegex will be allowed as a property not both. So this will allow either **none of these fields** OR **one of these fields** not both.
1. If neither are there, then the not subschema will pass, and the anyOf passes. (no applicationRegex, no applicationList is valid)
2. If one is there, then the oneOf subschema will pass, and the anyOf passes. (one of them is also valid)
3. If both are there, then
both of the oneOf subschemas will pass, so the oneOf fails
the not subschema will fail
so the anyOf fails (both of them is not valid)

feat: [CDS-98844]: Allow support for applicationRegex in Gitops Sync Step

---

v0/pipeline.json
v0/pipeline/steps/cd/delete-manifest-path-spec.yaml
v0/pipeline/steps/cd/k8s-apply-step-info.yaml
v0/pipeline/steps/cd/rollout-manifest-path-spec.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/delete-manifest-path-spec.yaml
v1/pipeline/steps/cd/k8s-apply-step-info.yaml
v1/pipeline/steps/cd/rollout-manifest-path-spec.yaml
v1/template.json

allow K8s Apply, Delete, Rollout & Patch steps to provide manifest paths as an expression

fix: [CDS-98140]: k8s - allow expression usage in paths parameter for apply/rollout/delete/patch steps

---

v0/pipeline.json
v0/pipeline/stages/ci/attestation-v1.yaml
v0/pipeline/stages/ci/cosign-attestation-v1.yaml
v0/pipeline/stages/ci/cosign-secret-manager-attestation-v1.yaml
v0/pipeline/steps/common/cosign-secret-manager-verify-attestation.yaml
v0/pipeline/steps/common/cosign-slsa-verify-attestation.yaml
v0/pipeline/steps/common/slsa-verify-attestation.yaml
v0/pipeline/steps/custom/attestation.yaml
v0/pipeline/steps/custom/cosign-attestation.yaml
v0/pipeline/steps/custom/cosign-secret-manager-attestation.yaml
v0/pipeline/steps/custom/cosign-secret-manager-verify-attestation.yaml
v0/pipeline/steps/custom/cosign-verify-attestation.yaml
v0/pipeline/steps/custom/verify-attestation.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/custom/attestation.yaml
v1/pipeline/steps/custom/cosign-attestation.yaml
v1/pipeline/steps/custom/cosign-secret-manager-attestation.yaml
v1/pipeline/steps/custom/cosign-secret-manager-verify-attestation.yaml
v1/pipeline/steps/custom/cosign-verify-attestation.yaml
v1/pipeline/steps/custom/verify-attestation.yaml
v1/template.json

**Description**
1. Modified schema for SSCA orchestration step to add vault attestation
2. Modify schema for SSCA Enforcement step to add vault attestation
3. Modify schema for SLSA Verification step to add vault attestation
I have tested the changes for backward compatibility all the steps are working fine . Here's the execution link 
https://kartikey366.pr2.harness.io/ng/account/WcI4OiuJTr-o2PSZwXuYkA/all/orgs/default/projects/Humanshu_Testing/pipelines/SSCA_and_SLSA/executions/1vYXiWGKStyf3le8jmmuOg/pipeline

feat:[SSCA-2392] : Modify schema for SSCA steps to add vault attestation and verify attestation

---

v0/pipeline.json
v0/pipeline/common/strategy-on-failure-type.yaml
v0/pipeline/stages/cd/deployment-stage-config.yaml
v0/pipeline/stages/cd/multi-deployment-config.yaml
v0/template.json

- Added the following in CD stage
```
multiDeploymentConfig:
onFailure: RunAll || SkipQueued
```
- Enum added in commons to be used at `strategy` level as well
- Product Spec: https://harness.atlassian.net/wiki/spaces/~62ac065cbfade2006967096e/pages/21966258289/Product+Spec+-+Matrix+Loop+Repeat+Failure+Handling
Local Testing
- In pipeline studio, only valid enum values should be allowed. 
- In pipeline studio, optional `onFailure` field
- In pipeline studio, optional `multiDeploymentConfig` field
- In template studio, only valid enum values should be allowed. 
- In template studio, optional `onFailure` field
- In template studio, optional `multiDeploymentConfig` field

feat: [CDS-100123]: On failure support for CD multi deployment

---

v0/pipeline.json
v0/pipeline/common/strategy-config.yaml
v0/template.json

- Added the following in CD stage
```
strategy:
onFailure: RunAll || SkipQueued
repeat/matrix/parallelism:
...
```
- Enum added in commons to be used at `strategy` level as well
- Product Spec: https://harness.atlassian.net/wiki/spaces/~62ac065cbfade2006967096e/pages/21966258289/Product+Spec+-+Matrix+Loop+Repeat+Failure+Handling
Local Testing
- In pipeline studio, only valid enum values should be allowed. 
- In pipeline studio, optional `onFailure` field
- In template studio, only valid enum values should be allowed. 
- In template studio, optional `onFailure` field

feat: [CDS-100629]: on_failure support for strategy config

---

v0/pipeline.json
v0/pipeline/steps/custom/approver-input-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/custom/approver-input-info.yaml
v1/template.json

Problem: For harness approval, currently we do not have regex or allowed values constraints on the approver inputs. Working on a feature to support that.
Changes:  
Added following fields : 
- allowedValues : List of values that have to be allowed for the variable. Individual values can be expression
- regex: Regex pattern to match with the variable. Pattern can be an expression 
- required : Boolean if the variable is a required field. It can be an expression. This is an optional field with the default as false.
Testing:
Tested locally with final pipeline to see that the yaml is working as expected for the added fields.

feat: [CDS-100884]: Added allowed values,regex,required field to harness approval inputs

---

v0/pipeline.json
v0/pipeline/steps/custom/approver-input-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/custom/approver-input-info.yaml
v1/template.json

Follow up of : https://github.com/harness/harness-schema/pull/440
Tech spec : https://harness.atlassian.net/wiki/spaces/CDNG/pages/22007154225/Tech+Spec+Runtime+Input+with+allowed+values+in+Manual+Approval+step
There were some changes made to yaml schema requirements. 
We have added another field selectOneFrom to support single select and multiselect
Added constraint that at most one of them can be present out of three: regex, allowedValues, selectOneFrom fields
Testing:
Tested locally by using the pipeline.json generated
Works as expected with at most one of the fields:
Throws schema error when we trying saving more than one for the same approver inputs

feat: [CDS-100884]: Modified approver input schema to incorporate selectOneFrom

---

v0/template.json
v0/template/workspace/template.yaml
v1/template.json
v1/template/workspace/template.yaml

What
Adds Terraform File Variables as an array of strings each with a file extension of .tf 
Moves Terraform Variables and Env Variables to Spec
Why
To Allow us to store terraform files in the template
To keep consistency

feat: [IAC-2478]: Add Terraform Variable Files to Schema, Move Variables to Spec

---

v0/pipeline.json
v0/pipeline/stages/cd/environment-group-yaml.yaml
v0/pipeline/stages/cd/environment-yaml-v2.yaml
v0/pipeline/stages/cd/environments-yaml.yaml
v0/pipeline/stages/cd/service-yaml-v2.yaml
v0/pipeline/stages/cd/services-yaml.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/stages/cd/environment-group-yaml.yaml
v1/pipeline/stages/cd/environment-yaml-v2.yaml
v1/pipeline/stages/cd/environments-yaml.yaml
v1/pipeline/stages/cd/service-yaml-v2.yaml
v1/pipeline/stages/cd/services-yaml.yaml
v1/template.json

Changes made:
Failure strategy added to following stage configurations:
1. Service
2. Services (for multiple services)
3. Environment
4. Environments (for multiple services)
5. EnvironmentGroup
Testing done:
Tested locally by using the generated pipeline.json 
If I change the configuration to provide improper error or action, validation fails.
Otherwise working fine for normal scenarios:
These are optional fields, so not having them causes no change to the existing yaml ensuring backward compatibility.

feat: [CDS-101268]:Schema changes for sevice/env failure strategy override

---

v0/template.json
v0/template/workspace/template.yaml
v1/template.json
v1/template/workspace/template.yaml

**What**
Adds locked to the required parts of the template
Updates the format of Terraform Variable files
**Why**
So we can implement usecase 2 of workspace templates
**Example Yaml**
```template:
name: demo-1
identifier: demo1
projectIdentifier: "default"
orgIdentifier: "default"
versionLabel: "1"
type: Workspace
spec:
cost_estimation:
enabled: true
budget: 1000
locked: true
provisioner:
type: terraform
version: 1.5.7
connector: account.awsscott
locked: false
repository:
isHarnessCode: false
connector: account.BBE_Repo_Consul
branch: master
gitFetchType: branch
path: /path/to/config
locked: true
variables:
- key: var1
value: "some value"
type: String
locked: true
- key: var2
value: 100
type: Number
locked: false
- key: secretVar
value: ENC[XXXXXX]
type: Secret
terraform_variables:
- key: …
```

IAC-2689 - Add locking and change variable file format

---

v0/pipeline.json
v0/pipeline/steps/ci/acrstep-info.yaml
v0/pipeline/steps/ci/docker-step-info.yaml
v0/pipeline/steps/ci/ecrstep-info.yaml
v0/pipeline/steps/ci/garstep-info.yaml
v0/pipeline/steps/ci/gcrstep-info.yaml
v0/template.json

What: Added support to use env variables and haress secrets as docker secrets for all the build and push steps. Why: To prevent leaking secrets in any layer of dockers final image.
https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/module/code/orgs/HarnessHCRInternalUAT/projects/Harness_Code/repos/harness-core/pulls/6601

fix:[CI-13924]: update schema for docker secrets

---

v0/pipeline.json
v0/pipeline/common/db-devops-failure-strategy-action-config.yaml
v0/pipeline/common/db-devops-failure-strategy-config.yaml
v0/pipeline/common/db-devops-on-failure-config.yaml
v0/pipeline/steps/common/dbops-apply-schema-step-node.yaml
v0/pipeline/steps/common/dbops-liquibase-command-step-node.yaml
v0/pipeline/steps/common/dbops-rollback-schema-step-node.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/common/db-devops-failure-strategy-action-config.yaml
v1/pipeline/common/db-devops-failure-strategy-config.yaml
v1/pipeline/common/db-devops-on-failure-config.yaml
v1/pipeline/steps/common/dbops-apply-schema-step-node.yaml
v1/pipeline/steps/common/dbops-rollback-schema-step-node.yaml
v1/template.json

Adding schema validations to only allow Pipeline and Stage Rollback actions in DB-DevOps steps failure strategy.

[fix]: [DBOPS-807]: Validation for rollback actions in DB-DevOps steps failure strategy

---

v0/pipeline.json
v0/pipeline/stages/cd/service-yaml-v2.yaml
v0/pipeline/stages/cd/services-yaml.yaml
v0/template.json

Actual PR: https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/module/code/orgs/HarnessHCRInternalUAT/projects/Harness_Code/repos/harness-core/pulls/70677 
https://harness.atlassian.net/browse/CDS-96644
We have introduces a disableArtifactValidation Field in the UI which will make validation of artifact field in run form optional . Also we would not pull the artifact details, if it is checked
Tests which are done are added in the doc below:
https://docs.google.com/spreadsheets/d/1D1RkY0L84U63L2bBTGilPwGg0Uy7iEGnBGgmB0UMIhk/edit?gid=0#gid=0
Tech Spec:
https://harness.atlassian.net/wiki/spaces/CDNG/pages/22163783747/Optional+Primary+Artifact+Support+in+Deploy+Stage

feat:[CDS-104595]: Schema Changes For DisableArtifactValidation Field

---

v0/pipeline.json
v0/pipeline/steps/common/gar-source-spec.yaml
v0/pipeline/steps/common/gcr-source-spec.yaml
v0/template.json

This pull request includes changes to update the required properties for various pipeline specifications by replacing `project` with `project_id`. The changes affect multiple JSON and YAML files.
Updates to required properties:
* [`v0/pipeline.json`](diffhunk://#diff-47707a8e6ec1ce8b8accc4042a2a481d7326e615194d86699b01aa0c5d8abab2L35383-R35383): Changed "required" property from `project` to `project_id` in two instances. [[1]](diffhunk://#diff-47707a8e6ec1ce8b8accc4042a2a481d7326e615194d86699b01aa0c5d8abab2L35383-R35383) [[2]](diffhunk://#diff-47707a8e6ec1ce8b8accc4042a2a481d7326e615194d86699b01aa0c5d8abab2L35467-R35467)
* [`v0/pipeline/steps/common/gar-source-spec.yaml`](diffhunk://#diff-253b340e597784bddc02ce88323ad1eb334d2ae7914aaf3672f6fc4e3d59bdf5L8-R8): Changed "required" property …

feat:[SSCA-3129]: Modified required fields in Gar and GCR Source spec

---

v0/template.json
v0/template/notification/template.yaml

The schema parser expects the schema in a specific format. While theh crud operations were working as expected, the templateSchema API which the UI uses in the local env, was returning no data for notification templates.
The title of the notification template was changed so that the ref generated can be parsed by the parser.

Fix notification template reference for the schema parser

---

v0/pipeline.json
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/template.json

This pull request includes a change to the `v0/pipeline/stages/cd/execution-wrapper-config.yaml` file, adding a new step to the pipeline configuration.
Pipeline configuration update:
* [`v0/pipeline/stages/cd/execution-wrapper-config.yaml`](diffhunk://#diff-b25b4e2410ebc4eb41e2f09236f3c1ae918e159d079a4afe88799a67517e9162R116): Added a reference to the `artifact-verification-step-node.yaml` file to include the artifact verification step in the pipeline.

feat:[SSCA-3302]: Added artifact verification step to deploy stage

---

v0/pipeline.json
v0/pipeline/steps/common/artifact-signing-source.yaml
v0/pipeline/steps/common/artifact-signing-step-info.yaml
v0/pipeline/steps/common/local-source-spec.yaml
v0/template.json

This pull request introduces support for a new source type, "local", in the pipeline configuration. The changes span multiple files and involve adding new schema definitions and updating existing ones to accommodate the new source type.
Key changes include:
* [`v0/pipeline.json`](diffhunk://#diff-47707a8e6ec1ce8b8accc4042a2a481d7326e615194d86699b01aa0c5d8abab2R29744-R29758): Added a new conditional block to handle the "local" source type and defined a new `LocalSourceSpec` schema. This includes specifying required properties such as `workspace` and `artifact_name`, and adding the "local" type to the existing enum list. [[1]](diffhunk://#diff-47707a8e6ec1ce8b8accc4042a2a481d7326e615194d86699b01aa0c5d8abab2R29744-R29758) [[2]](diffhunk://#diff-47707a8e6ec1ce8b8accc4042a2a481d7326e615194d8669 …

feat:[SSCA-3356]: Added support for non container artifacts to Artifact Signing and Artifact Verification Step

---

v0/pipeline/steps/common/local-source-spec.yaml

This pull request includes a change to the `v0/pipeline/steps/common/local-source-spec.yaml` file to remove the `artifact_name` property from the `required` list.
* [`v0/pipeline/steps/common/local-source-spec.yaml`](diffhunk://#diff-02f13fd3789eaeb144be408c65e6b3be706eb401741927b8ff87a975a03db81aL7): Removed `artifact_name` from the `required` list.

feat:[SSCA-3356]: Making artifact_name not mandatory

---

v0/pipeline.json
v0/pipeline/steps/common/artifact-signing-source.yaml
v0/template.json

This pull request includes several changes to the `v0/pipeline.json`, `v0/template.json`, and `v0/pipeline/steps/common/artifact-signing-source.yaml` files to add support for a new "local" artifact signing source and to modify the required properties for certain objects. The most important changes are:
Support for new "local" artifact signing source:
* Added "local" to the `enum` list for the `type` property in `v0/pipeline.json`.
* Added "local" to the `enum` list for the `type` property in `v0/template.json`.
* Added "local" to the `enum` list for the `type` property in `v0/pipeline/steps/common/artifact-signing-source.yaml`.
Modification of required properties:
* Removed `artifact_name` from the `required` list in `v0/pipeline.json`.
* Removed `artifact_name` from the `required` list …

feat:[SSCA-3356]: Added new enum type for signing and verification

---

v0/pipeline.json
v0/pipeline/steps/cd/terraform-cloud-plan-and-apply-spec.yaml
v0/pipeline/steps/cd/terraform-cloud-plan-and-destroy-spec.yaml
v0/pipeline/steps/cd/terraform-cloud-plan-only-spec.yaml
v0/pipeline/steps/cd/terraform-cloud-plan-spec.yaml
v0/pipeline/steps/cd/terraform-cloud-refresh-spec.yaml
v0/template.json

This PR includes the schema changes for new **Optional** field: **Project** for Terraform Cloud Run.
Below are the Run Type it is applicable for:
1. Plan
2. Plan Only
3. Plan and Destroy
4. Plan and Apply
5. Refresh

feat: [CDS-107618]: schema changes for new field Project

---

v0/pipeline.json
v0/pipeline/steps/common/aws-cdk-bootstrap-step-info.yaml
v0/pipeline/steps/common/aws-cdk-deploy-step-info.yaml
v0/pipeline/steps/common/aws-cdk-destroy-step-info.yaml
v0/pipeline/steps/common/aws-cdk-diff-step-info.yaml
v0/pipeline/steps/common/aws-cdk-synth-step-info.yaml
v0/template.json

In CDK steps currently customers have to provide access and secret keys in env variables as shown in screenshot below. 
We want to add a optional connector that if provided can be used to derive these

Feat: [CDS-107999]: Schema changes: accept opt AWS connector in CDK steps

---

v0/pipeline.json
v0/pipeline/stages/cd/multi-deployment-config.yaml
v0/template.json

Allow runtime input in maxConcurrency for multiService deployment
Tested that pipeline can only be saved with integer value and runtime input

feat: [CDS-107795]: Allow runtime input in maxConcurrency for multiService deployment

---

v0/pipeline.json
v0/template.json
v0/template/pipeline/pipeline_spec.yaml

feat: [PIPE-26132]: fix Pipeline Templates do not allow for Expressions for Delegate Selectors
Testing done :
* With my changes ( local env )
* Without my changes ( prod env )
* Verified that the expressions are also getting resolved in the delegate selectors
YAML ->
```
pipeline:
identifier: gfh
name: gfh
tags: {}
stages:
- stage:
name: Test
identifier: Test
description: ""
type: Custom
spec:
execution:
steps:
- step:
type: ShellScript
name: ShellScript_1
identifier: ShellScript_1
spec:
shell: Bash
executionTarget: {}
source:
type: Inline
spec:
script: echo <+pipeline.variables.delegates>
environmentVariables: []
outputVariables: []
timeout: 10m
tags: {}
variables:
- name: delegates
type: String
description: ""
required: false
value: "docker-delegate,kubernetes-delegate-harnessgcp" …
```

feat: [PIPE-26132]: fix Pipeline Templates do not allow for Expressions for Delegate Selectors

---

v0/pipeline.json
v0/pipeline/steps/common/local-source-spec.yaml
v0/template.json

This pull request includes changes to the JSON schema definitions and YAML specifications to introduce a new `type` property with conditional requirements for `artifact_name` and `version` properties. The most important changes are as follows:
* [`v0/pipeline.json`](diffhunk://#diff-47707a8e6ec1ce8b8accc4042a2a481d7326e615194d86699b01aa0c5d8abab2L18184-R18219): Added a new `type` property with `manual` and `auto` options to the required properties list. Introduced conditional requirements for `artifact_name` and `version` properties when `type` is `manual`.
* [`v0/template.json`](diffhunk://#diff-6c0f24251df68b230837bfd880ada4985d7b2b49d80929c20bfa14bac2c7673cL58981-R59016): Similar to changes in `v0/pipeline.json`, added a new `type` property and conditional requirements for …

feat:[SSCA-3580]: Added auto and manual detection for Non Container Artifact Signing and Aritfact Verification

---

v0/pipeline.json
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/pipeline/steps/cd/alb-target-group-tuple.yaml
v0/pipeline/steps/cd/ecs-blue-green-create-service-step-info.yaml
v0/pipeline/steps/cd/ecs-blue-green-traffic-shift-step-info.yaml
v0/pipeline/steps/cd/ecs-blue-green-traffic-shift-step-node.yaml
v0/pipeline/steps/cd/ecs-traffic-shift-spec.yaml
v0/pipeline/steps/cd/ecs-traffic-shift-wrapper.yaml
v0/pipeline/steps/cd/inherit-ecs-traffic-shift-spec.yaml
v0/pipeline/steps/cd/stand-alone-ecs-traffic-shift-spec.yaml
v0/pipeline/steps/cd/stand-alone-traffic-shift-rollback-step-info.yaml
v0/pipeline/steps/cd/stand-alone-traffic-shift-rollback-step-node.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/stages/cd/execution-wrapper-config.yaml
v1/pipeline/steps/cd/alb-target-group-tuple.yaml
v1/pipeline/steps/cd/ecs-blue-green-create-service-step-info.yaml
v1/pipeline/steps/cd/ecs-blue-green-traffic-shift-step-info.yaml
v1/pipeline/steps/cd/ecs-blue-green-traffic-shift-step-node.yaml
v1/pipeline/steps/cd/ecs-traffic-shift-spec.yaml
v1/pipeline/steps/cd/ecs-traffic-shift-wrapper.yaml
v1/pipeline/steps/cd/inherit-ecs-traffic-shift-spec.yaml
v1/pipeline/steps/cd/stand-alone-ecs-traffic-shift-spec.yaml
v1/pipeline/steps/cd/stand-alone-traffic-shift-rollback-step-info.yaml
v1/pipeline/steps/cd/stand-alone-traffic-shift-rollback-step-node.yaml
v1/template.json

Tech Spec: https://harness.atlassian.net/wiki/spaces/CDNG/pages/22178104525/Tech+Spec+Support+Traffic+shift+during+ECS+BG+deployment#LLD-for-Final-Proposal-for-dual-BG-traffic-shifting-step-in-ECS
Functional PR: https://harness0.harness.io/ng/account/l7B_kbSEQD2wjrM7PShm5w/module/code/orgs/PROD/projects/Harness_Commons/repos/harness-core/pulls/101735
ECS Traffic Shift Step
- `ecsTrafficShiftWrapper` is required. 
- `type` and `spec` are required in `ecsTrafficShiftWrapper`
- `type` can be only ` "Standalone", "Inherit"`
-  **Inherit**: 
`weightPercentage` required for inherit , can be between 0 to 100 inclusive only for fixed value, or runtime input or expression
- **StandAlone**: 
`loadBalancer` : required, blank value not allowed or runtime input or expression
`listener` : required, …

feat: [CDS-105760]: schema changes for ecs traffic shifting

---

v0/pipeline.json
v0/pipeline/steps/cd/helm-canary-step-info.yaml
v0/pipeline/steps/cd/helm-deploy-step-info.yaml
v0/pipeline/steps/cd/helm-stage-step-info.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/steps/cd/helm-canary-step-info.yaml
v1/pipeline/steps/cd/helm-deploy-step-info.yaml
v1/pipeline/steps/cd/helm-stage-step-info.yaml
v1/template.json

- Allow users to specify, using a step flag, whether Helm should use the CLI `helm install` command or `helm upgrade --install` for service deployment.
- Named the new flag "**Use Upgrade with Install**" which easily describes what backend is doing

feat:[CDS-108186]: Add flag in harness helm deployment steps to skip helm install

---

v0/template.json
v0/template/workspace/template.yaml
v1/template.json
v1/template/workspace/template.yaml

This pull request introduces a new `defaultPipelines` object to the schema definitions in both `v0` and `v1` templates. This object defines properties related to pipeline configurations, such as `plan`, `apply`, `destroy`, `drift`, and `locked`. These changes ensure consistency across JSON and YAML schema files for both versions.
* **`v0/template.json`**: Added a `defaultPipelines` object with properties (`plan`, `apply`, `destroy`, `drift`, `locked`) to the schema.
* **`v0/template/workspace/template.yaml`**: Mirrored the `defaultPipelines` object and its properties in the YAML schema.
* **`v1/template.json`**: Introduced the `defaultPipelines` object with the same properties as in `v0/template.json`.
* **`v1/template/workspace/template.yaml`**: Added the `defaultPipelines` object and …

feat: [IAC-3519]: Add defaultPipelines to workspace template schema

---

v0/pipeline.json
v0/pipeline/steps/cd/aws-load-balancer-config-yaml.yaml
v0/template.json

Tech Spec: https://harness.atlassian.net/wiki/spaces/CDNG/pages/22307799569/Spot+Dual-Mode+Traffic+Shifting+support
This PR contains changes to Elastigroup BG Stage setup step for supporting traffic shifting : 
- `stageListenerPort` , `stageListenerRuleArn` are made optional
- `isTrafficShift` optional boolean field added
- `stageTargetGroupArn` new optional string field:
Example yaml for traffic shifting flow 
```
loadBalancers:
- type: AWSLoadBalancerConfig
spec:
loadBalancer: namanSpot
isTrafficShift: true
prodListenerPort: "8080"
prodListenerRuleArn: <+random>
stageTargetGroupArn: arn:aws:elasticloadbalancing:us-east-1:839162981415:targetgroup/namanTest80/8b7b2657b4a7a360
```
Example yaml for non-traffic shifting flow 
```
loadBalancers:
- type: AWSLoadBalancerConfig
spec: …
```

feat: [CDS-109193]: Spot traffic shifting schema changes for existing steps

---

v0/pipeline.json
v0/pipeline/stages/cd/execution-wrapper-config.yaml
v0/pipeline/steps/cd/elastigroup-blue-green-traffic-shift-step-info.yaml
v0/pipeline/steps/cd/elastigroup-blue-green-traffic-shift-step-node.yaml
v0/pipeline/steps/cd/elastigroup-traffic-shift-spec.yaml
v0/pipeline/steps/cd/elastigroup-traffic-shift-wrapper.yaml
v0/pipeline/steps/cd/inherit-elastigroup-traffic-shift-spec.yaml
v0/pipeline/steps/cd/stand-alone-elastigroup-traffic-shift-spec.yaml
v0/template.json

Tech Spec: 
https://harness.atlassian.net/wiki/spaces/CDNG/pages/22307799569/Spot+Dual-Mode+Traffic+Shifting+support
Step Pojo PR: https://harness0.harness.io/ng/account/l7B_kbSEQD2wjrM7PShm5w/module/code/orgs/PROD/projects/Harness_Commons/repos/harness-core/pulls/102625
Elastigroup Traffic Shift Step
- `elastigroupTrafficShiftWrapper` is required. 
- `type` and `spec` are required in `elastigroupTrafficShiftWrapper`
- `type` can be only ` "Standalone", "Inherit"`
-  **Inherit**: 
`weightPercentage` required for inherit , can be between 0 to 100 inclusive only for fixed value, or runtime input or expression
- **StandAlone**: 
`loadBalancer` : required, blank value not allowed or runtime input or expression
`listenerArn` : required, blank value not allowed or runtime input or expression …

feat: [CDS-109192]: Spot traffic shift step

---

v0/template.json
v0/template/notification/notification_template_body.yaml

We consider and parse the content in the schema as a string, across the FE behaviour and the backend code.
However, due to the added suupoort of object in the schema, UI visual breaks, as it considers the content to be a string.
Removing the '|' in the yaml , should therefore result in a schema validation error, instead of breaking the UI.

Removed the support of object in the notification template schema

---

v0/pipeline.json
v0/pipeline/stages/iacm/execution-wrapper-config.yaml
v0/pipeline/steps/iacm/iacmterragrunt-plugin-info.yaml
v0/pipeline/steps/iacm/iacmterragrunt-plugin-step-node.yaml
v0/template.json
v1/pipeline.json
v1/pipeline/stages/iacm/execution-wrapper-config.yaml
v1/pipeline/steps/iacm/iacmterragrunt-plugin-info.yaml
v1/pipeline/steps/iacm/iacmterragrunt-plugin-step-node.yaml
v1/template.json

Added schema definitions for the Terragrunt step in IACM pipeline, following the same pattern as existing Terraform and OpenTofu steps. This addition will enable Terragrunt support in the YAML editor with proper auto-intellisense capabilities.
1. Added new schema files in v0:
- `v0/pipeline/steps/iacm/iacmterragrunt-plugin-info.yaml`: Defines the Terragrunt step configuration
- `v0/pipeline/steps/iacm/iacmterragrunt-plugin-step-node.yaml`: Defines the step node structure
- Updated `v0/pipeline/stages/iacm/execution-wrapper-config.yaml` to include Terragrunt step
2. Added corresponding schema files in v1:
- [v1/pipeline/steps/iacm/iacmterragrunt-plugin-info.yaml](cci:7://file:///Users/rajendrabaviskar/harness-schema/v1/pipeline/steps/iacm/iacmterragrunt-plugin-info.yaml:0:0-0:0)
- …

feat:[IAC-3673]: adding Iacm TG step

---

v0/template.json
v0/template/workspace/template.yaml
v1/template.json
v1/template/workspace/template.yaml

This pull request introduces new fields, `description` and `tags`, to the template schema across multiple versions (`v0` and `v1`). These changes enhance the schema by allowing additional metadata to be associated with templates.
Schema updates:
* [`v0/template.json`](diffhunk://#diff-6c0f24251df68b230837bfd880ada4985d7b2b49d80929c20bfa14bac2c7673cR1067-R1075): Added `description` (type: string) and `tags` (type: array of strings) fields to the template schema.
* [`v0/template/workspace/template.yaml`](diffhunk://#diff-37d7dc4b7e81158925cb7e71c26db3f8ce363f41742aac4cd5ae2a80b9cdc21bR22-R27): Added `description` and `tags` fields with corresponding types to the workspace template schema.
* [`v1/template.json`](diffhunk://#diff-0397c2f1db0c2902bc79c0a01d74f44496e170634c80fc3894c2d04dfc2af6be …

feat: [IAC-3904]: Add desc and tags for workspace templates
